### ISSUE TITLE
React component library is no longer injected

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#102]
The server has stopped injecting the script. 

Instead we just see
```
<!--dynamically include version running in environment-->
<!--#include virtual='/gbif-components.inc' -->
```

Currently that means that no data widgets work if they have been deployed since the bug was introduced

**Comment by MortenHofft** [comment]
This could be fixed in the client by having a fallback, but I'd rather not as it would mask the problem.

```
<script>window.gbifReactComponents || document.write('<script src="https://react-components.gbif-staging.org/lib/gbif-react-components.js">\x3C/script>')</script>
```

**Comment by MattBlissett** [comment]
Fixed, sorry, there was a bug in the deployment script.  There's no need for a workaround.

**Comment by MortenHofft** [comment]
Thank you Matt, it still doesn't work for translations though. And also be aware that the url `/data` is configurable. it could be anything, so the replacement cannot just run on a specific url.

**Comment by MattBlissett** [comment]
Is it defined by the pages with `layout: occurrence` in the front matter?
