### ISSUE TITLE
Data Page - Filter order

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#107]
Looking at  #20  I realized that changing the positions of filters also will be nice,  particularly taking out from the "more  tab"  1 or 2 more filters, for example stateProvince and/or Administrative area that are very used criteria.

BTW The "DWCA extensions" option will be availabe at "more" tab?

**Comment by albenson-usgs** [comment]
BISON would also like to move "Administrative area" out of the "More" tab and also rename it to something that will be more meaningful for users.

**Comment by MortenHofft** [comment]
related to https://github.com/gbif/hosted-portals/issues/84

**Comment by MortenHofft** [comment]
See [docs](https://hp-theme.gbif-staging.org/data-exploration-config#occurrence-filters) for instructions.

```
var siteConfig = {
  rootPredicate: ...,
  blacklistedFilters: ['datasetKey'],
  highlightedFilters: ['collectionCode', 'taxonKey'],
```

**Comment by MortenHofft** [comment]
> also rename it to something that will be more meaningful for users.

At some point all filter names and ui labels will be in a translation file and available in Crowdin. English is however different than other languages, in the sense that I the GBIF secretariat provides those labels. But I'm sure feedback is appreciated if the labels are confusing/misleading/insensitive etc.

The flow for translating GBIF.org is 
* Some web developer (say me) write labels to the best of their ability
* GBIF communications translate that into proper english (Oxford english variation I believe) and sometimes change the wording entirely
* The translators translate the corrected english version to the various languages.

I imagine it will be something similar for this UI

**Comment by MattBlissett** [comment]
GBIF's house style is to follow the [UN style guide](https://www.un.org/dgacm/en/content/editorial-manual), which is [Oxford English](https://en.wikipedia.org/wiki/Oxford_spelling) (realize, colour). Except we use Darwin Core terms as they are defined (catalog number, coordinate uncertainty in meters — not catalogue or metres).

If we need to, we could create American English (realize, color) and British English (realise, colour) translations; only a few words would need translating.
