### ISSUE TITLE
Use of <iframe> elements

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hosted-portals#109]
Would it be possible to use `<iframe>` elements in the hosted portal pages?

Specifically, we would like to have active content within news items. For example, when we hold quarterly regional online meetings, having a live Jamboard or Google Doc would be beneficial and could increase participation. However, these require `<iframe>`.

**Comment by MortenHofft** [comment]
Yes - The [Colombian site](https://hp-colombian-biodiversity.gbif-staging.org/buscar/gacetero) already have an example - notice that the page is structured a bit differently to have a larger iframe, and that a bit of custom css is added. The [demo site](https://hp-theme.gbif-staging.org/markdown#video) video is also an iframe.

@RicardoOrtizG perhaps you have any recommendations?

**Comment by MortenHofft** [comment]
@jenningsdt let me know if you need help with the specific use case.

**Comment by RicardoOrtizG** [comment]
Hi!

We add iframes for youtube videos and google forms just by copying the iframe brackets (you can found them in the share options of each application) directly to the Markdown text. ([Google Forms example] (https://hp-colombian-biodiversity.gbif-staging.org/share/registrate), [Example of videos in dropdown buttons] (https: //hp-colombian-biodiversity.gbif-staging. org / community / training / CicloFormacion2020 # seminars)). It is very simple and more responsive in cellphones or tablets. The other way is adding a custom and making a class in which you can add the iframe.

As Morten says you can customize it by adding some CSS as shown [here] (https://github.com/gbif/hp-colombian-biodiversity/blob/master/_sass/_main.scss) in the. iframe-box object. and adding the iframes in the section [custom.yml] (https://github.com/gbif/hp-colombian-biodiversity/blob/master/_data/custom.yml) as shown in gacetero: and formularioRegistro:

Hope it is useful to you.
