### ISSUE TITLE
Shared news source among the hosted portals

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hosted-portals#110]
It would be nice to have some mechanism to share news items among portals short of copying and pasting the posts themselves. Our team was discussing that there may be news items generated by one portal that are relevant and/or could be amplified by other portals. So, having some sort of shared news source would eliminate a lot of duplication, re-translation, and propensity for error.

**Comment by MortenHofft** [comment]
My gut feeling is that this is outside the scope of a the Jekyll theme. If you however find a good way to do it, then it might be interesting to others.

**Ideas**
* You could use an rss feed and add those news in Javascript to your respective portals using the template of your choice. 
* Or find/write a Jekyll plugin that allows you to generate pages from a feed or other source (I know Contentful can be used as a source), any change to that could trigger a build of both sites.
* Or perhaps git submodules could be used?

If this is a general problem with wider interest, then I can also look into options, but I do not imagine it belongs in the Jekyll theme.

**Comment by MortenHofft** [comment]
I don't like to close things as "won't fix", but I'm going to. Let me know if you believe this is a tragic misunderstanding and should be part of the Jekyll theme or otherwise developed for the benefit of other participants.
