### ISSUE TITLE
Publications related to the portal scope

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hosted-portals#111]
It would be great to be able to see the publications related to a portal's specific scope similar to what you can see when doing a search on GBIF (`contentType=literature`) or on the country pages (https://www.gbif.org/country/US/publications/about).

**Comment by MortenHofft** [comment]
I forgot to comment on this issue. We do not track citations on an occurrence level, only on a dataset level. Meaning that we do not know which occurrences are used, only which datasets are used (and from that we can deduce higher levels like publisher and country).

So this is not an option to do based on the occurrence scope. It would have to be specified separately. But we can make the literature search available, but it might not be possible to scope it as you wish. So:
* the legume site wouldn't be able to create a filter on literature that only showed citations making use of the legume occurrences. 
* For sites with a country scope it should be possible.

**Comment by MortenHofft** [comment]
Development is in progress and is [visible online](https://react-components.gbif-staging.org/iframe.html?id=search-literaturesearch--example&args=&viewMode=story), but is not ready for adding to any sites

**Comment by MortenHofft** [comment]
Hi @jenningsdt 
I think this is in a state that it makes sense to discuss how to proceed. There are a couple of things that I'm not sure how to handle and I'm not entirely sure what is expected either. If it is okay with you we could use the North American site as an example implementation. The site isn't live yet and it might be nice to see something concrete?

**Comment by jenningsdt** [comment]
This sounds like a nice idea, @MortenHofft . Thanks on behalf of our team!

**Comment by MortenHofft** [comment]
I've changed the data menu item to a dropdown with links to occurrence search as well as 3 versions of literature search (same ui, but different filters).

* All: One is showing all literature items (not scoped by portal)
from: One is showing only papers from north america researchers
about: and the last is showing papers covering north america

I'm not sure how I think these are best used. What is your thoughts?

--------

My first concern is context. I find that some header or similar telling me what I look at would be useful. iI wasn't so much an issue when we had one search, but if we extend to literature and possibly datasets and publishers, then I think I would miss it. Could be as simple as a headline stating the content type similar to GBIF.org

<img width="1430" alt="Screenshot 2021-08-24 at 13 00 59" src="https://user-images.githubusercontent.com/6759267/130605470-9eae80bb-a6c1-4870-a915-6a290d452561.png">

My second concern would be that literature search is split in two. Which might be okay, but it is also a bit odd. But having them as one isn't an option currently as the API do not allow for showing papers that are either from or about north america. And even if we extended the API to allow that, then I'm not sure it would be easier to understand.

**Comment by albenson-usgs** [comment]
Thanks for adding this Morten! It's a really nice addition. Here are some thoughts from the GBIF North America Steering Group (it's not a full consensus so others may add more later):

1. Overall it looks great and will be a great addition to the portal. We like the search features and the altmetric.
2. We were confused about the "Literature all" option which is not scoped to the portal. We expect people would want to go to GBIF proper for this. We would opt to remove that option.
3. Some of us didn't like the literature as a drop down on the Data tab and would prefer it as its own tab.

We are still thinking about your two concerns but don't have opinions on it just yet. We'll come back with more on those soon.

**Comment by mbelisle** [comment]
Thank you for this feature. It is quite useful, and I have just added it to our site.
I agree with all three points brought up by Abby, though we haven't discussed these more widely.  I will provide additional feedback once we have a committee in place.

**Comment by MortenHofft** [comment]
Thank you for your comments

The intention was never to have 3 menu items, but to show you the options we have available. Currently our options are: 
* 1 menu item (that includes everything)  OR
* 2 menu items (from+about). 

Where those are located in the menu is completely up to you in your website.

**Comment by albenson-usgs** [comment]
That makes sense Morten. The GBIF-US portal will be launching on Friday. I'd like to get this added if possible. Is it ready to be added to other portals? Can you help me with how to do it?

**Comment by MortenHofft** [comment]
If this is to be public, then I would like to remove the Altmetric column first https://github.com/gbif/hosted-portals/issues/178#issuecomment-929180196

I can help with the setup as needed. you can also see the related commit for the North American site 
https://github.com/gbif/hp-north-america/commit/4b525bae815b1db359c15b10d90ed390a65f5cea

**Comment by MortenHofft** [comment]
No I it isn't really ready to be added in production yet. The integration with the theme needs some work first, so the way it is added will change (which of course isn't ideal once it is live). But I can look to make it more stable

**Comment by albenson-usgs** [comment]
Ok good to know. I'll hold off and wait to add it when it's in a production state. Thanks!

**Comment by MortenHofft** [comment]
Since there has been no real protests with how this work and @mbelisle and @albenson-usgs wants to add it to their sites, then I will consider this a good enough solution. Changing this at a later point is possible, but will likely require all participants using the literature widget to change the way they use this

Hi @albenson-usgs I've changed the way it is included now to a format that I'm more happy with going forward. Feel free to add it. You can see the 3 versions here https://github.com/gbif/hp-north-america/tree/master/literature
Let me know if you need help
