### ISSUE TITLE
Translation | dates on posts

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#114]
@MortenHofft  How can we translate the dates of the posts? 

<img width="408" alt="Captura de Pantalla 2021-03-17 a la(s) 6 11 00 p  m" src="https://user-images.githubusercontent.com/5700527/111550528-4d5ae980-874c-11eb-9579-14015c2ec0bc.png">

Thank you in advance

**Comment by MortenHofft** [comment]
No but it is a very reasonable request.

* On posts it use the `preTitle` from the front matter.
* On cards it use the date formatted as english.

**Pragmatic solution**
When briefly looking I couldn't find any Jekyll plugins that handled just the dates. And after giving it some thought I like the simplicity and freedom of just making it a text field.

It could also be argued that posts doesn't have to be used as news with dates. So, I've opted for using the `preTitle` property on cards as we do on posts anyway. That gives editors the freedom to write want they want. Could be a date in any language. It could be anything really.

**Automate it**
If someone finds it frustrating having to write dates on posts, then I'm very open to a pull request. 
The approach should probably be something along: a Jekyll plugin that can localize dates. And an option in _config to use dates over preTitle for posts.

**Comment by MortenHofft** [comment]
Closed by
https://github.com/gbif/jekyll-hp-base-theme/commit/393149d650c9676c9e8db323a4fa31cc6e96a105
