### ISSUE TITLE
Translation | toc title

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#115]
Hi @MortenHofft ! Me again :sweat_smile: How can we translate the toc title 'ON THIS PAGE'?

**Comment by MortenHofft** [comment]
You are spotting real oversights, so it is great that you create issues for it.

Again - you cannot. That is a bug

**Comment by camiplata** [comment]
@MortenHofft I see you have close this issue, I'm guesing this part will be added to crowding for transaltion. I'm rigth?

**Comment by MortenHofft** [comment]
No, you do that in your [translation file](https://github.com/gbif/hp-colombian-biodiversity/blob/master/_data/translations.yml)
See https://hp-theme.gbif-staging.org/translations#add-translations-of-labels

Crowdin is only used to translate the data widgets

**Comment by camiplata** [comment]
Got it, thnaks!

**Comment by bienflorencia** [comment]
Came looking for this :) Thanks, @camiplata!
