### ISSUE TITLE
Selecting columns to display?

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/hosted-portals#120]
Would it be possible to make the columns that are displayed on the Data page customizable by the user? E.g. they could make the column Country appear or disappear, or e.g. Basis of record appear. Thanks!

**Comment by MortenHofft** [comment]
Related to https://github.com/gbif/hosted-portals/issues/120

**Comment by tucotuco** [comment]
Was there some other issue this was related to? The link is self-referential.

**Comment by MortenHofft** [comment]
This is now possible. See the documentation https://hp-theme.gbif-staging.org/data-exploration-config#default-columns-in-occurrence-table
and an example use https://github.com/gbif/hp-nhm-rotterdam/commit/42557248f5302d52218912902428f7dee89ce6ee

**Comment by MortenHofft** [comment]
I haven't added all DarwinCore fields as possible columns. If you miss any specific ones, then please create an issue and I will add it.

**Comment by langeveldNMR** [comment]
Thanks! Would it be possible to add the field 'preparations' to this and to also make it searchable for users on the data page? In our case it contains important information, such as whether a record consists of an entire specimen, or only its skeleton or soft tissue.

**Comment by MortenHofft** [comment]
I can add preparations as a table column, but to add it as a filter then we need download support for it. Could you please create an issue/feature request in https://github.com/gbif/pipelines/issues/new to add download and filter support for `preparations`?

**Comment by langeveldNMR** [comment]
Thanks for adding it as a table column this quickly. Much appreciated.

**Comment by langeveldNMR** [comment]
Preparations as a table column works fine on https://hp-nhm-rotterdam.gbif-staging.org/data but it does not appear on https://specimens.hetnatuurhistorisch.nl/data after the most recent release. Catalogue number does, however. Am I missing something?

**Comment by MortenHofft** [comment]
You are not. I just wasn't eager to do a production release just before going on vacation. This is a recurring cause of confusion: that the data widgets aren't always the same between staging and production. The two a deployed independently. I will create an issue to discuss if we should make use of prod in your staging environments to avoid this confusion.
