### ISSUE TITLE
Occurrence detail: Data contained in Gadm?

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/hosted-portals#123]
In some records, the field Gadm is shown in the summary, in our portal e.g. with specimen NMR996800078335, see https://hp-nhm-rotterdam.gbif-staging.org/data?entity=2570262240&filter=eyJtdXN0Ijp7InEiOlsiTk1SOTk2ODAwMDc4MzM1Il19fQ%3D%3D This field in many cases with our data contains outdated topographical information on the municipality level for Dutch localities. Why is this included and how is it generated? We do not export it to GBIF ourselves.

**Comment by MortenHofft** [comment]
[GADM](https://gadm.org/) is an interpretation layer. It is deduced from the coordinates and matched to GADM. It should be read as:
> According to GADM this point is located in `Netherlands > Zuid-Holland > Nederlek`

It is useful as it can be applied across records unlike the free text field locality. And hence allow for breakdowns and search per GADM country/county/municipality/district/region etc.

The uncontrolled dwc terms `locality` and `state province` is the cause of issues and misunderstandings on GBIF.org where users assume that a search for `stateProvince: Florida` will return all records in `Florida`. It will in fact return results where the record owner has filled that field with that exact word. For GADM however it will get its value based on coordinates (which is far more often filled) - and the spelling is normalized to a shared vocabulary.

If GADM is wrong, then it should ideally be fixed at source. @MattBlissett what is the procedure for getting GADM updated? Do we just leave an issue with GADM and hope it will be changed in the next version?

**Comment by MattBlissett** [comment]
Hi,

The data is from the GADM database version 3.6, i.e. https://gadm.org/maps/NLD_1.html

Just from https://en.wikipedia.org/wiki/List_of_municipalities_in_South_Holland I can see this is some years out of date.  It would be best if the GADM database were updated, i.e. by contacting the maintainer.  Could you do that, @langeveldNMR, perhaps with a better source than Wikipedia?  Or else let us know a source for the data and we can pass it on.

**Comment by tucotuco** [comment]
I have forwarded this message to GADM. Ideally, the suggested correction
and a source for it should be sent to gadm using
http://rasterra.com/contact/gadm_contact_form.

**Comment by langeveldNMR** [comment]
Thanks all! I have asked my colleague to contact GADM with the right current source using the contact form.

**Comment by MattBlissett** [comment]
Hi @langeveldNMR,

Would you mind looking at the regional boundaries for the Netherlands in GeoBoundaries, and seeing if they are more up-to-date?  We are considering using these boundaries instead of GADM. (Just an initial investigation at this point.)

https://www.geoboundaries.org/geoContrast.html?country=NLD&mainSource=geoBoundaries+%28Open%29&comparisonSource=GADM+v3.6&mainLevel=2&comparisonLevel=2

It would be best to comment on https://github.com/gbif/portal-feedback/issues/3068 as the problem isn't related to the hosted portals.

**Comment by abubelinha** [comment]
> It would be best to comment on https://github.com/gbif/portal-feedback/issues/3068 as the problem isn't related to the hosted portals.

@MattBlissett  I [commented](https://github.com/gbif/portal-feedback/issues/3068#issuecomment-1040070694) something there.
