### ISSUE TITLE
Data page blank

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/hosted-portals#131]
There seems to be a bug now that we've reordered the tabs on the data page for the North America portal. When you click data the page is blank. To get something to come up you have to click on one of the tabs.
<img width="687" alt="blankdata" src="https://user-images.githubusercontent.com/7586150/114762886-7062c400-9d1f-11eb-9a64-db5fe104e627.PNG">

**Comment by MortenHofft** [comment]
Indeed - I changed it to uppercase to indicate an enumeration value. And forgot that the value was used in existing URLs (the data link in the NA portal says `view=map` and it is now `view=MAP`. 

And invalid values mean that nothing is shown

**Comment by MortenHofft** [comment]
I've changed the link https://github.com/gbif/hp-north-america/commit/00375af535465838bcbd2861ae8e91211a76629d as part of a bulk update to those portals that used the previous URL format. Something similar will probably happen again while we are in development. Things won't be entirely stable I'm afraid.
