### ISSUE TITLE
Proof read help texts for filters

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#133]
Proof read texts, or even just cursory :)

The filter names, help texts and placeholders are often wrong (they are semi generated from a script). Example of wrong value is: `Locality` filter has a search box that says "e.g. DNA sequence reads"

The help texts will go into a translation file later, but having a sensible starting point makes the whole thing easier

**Comment by tucotuco** [comment]
Is this the same as Issue #60?

**Comment by MortenHofft** [comment]
Yes it is - or at best a spelled out version of the placeholder content. I'm closing it. thank you for spotting that!
