### ISSUE TITLE
Placeholder texts

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#134]
In the UI we have made room for about texts for each filter. But someone has to write those descriptions.
https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/locales/en.js#L229

We might not want if for all - or we might not have it for all to begin with. So for now we should either add an about text or remove the text (by removing the [key](https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/locales/en.js#L229), the about option will disappear).

Similar we have placeholder texts for input "placeholder" i.e. the greyed out text in search boxes.

**Comment by tucotuco** [comment]
Are these customizable within hosted portal instances?

**Comment by MortenHofft** [comment]
No - that isn't the intention. The idea is to have a shared version (managed in Crowdin). So that e.g. all spanish version have the same help texts. If there is disagreements on what a help text should be, then that discussion can take place in Crowdin among the translators. Or if different variations of spanish is needed and there is a desire among the translators to have spanish in Pan-American, Caribbean and Catalan then that is fine. 

If there is a desire to customise messages on an instance level, then I see no technical challenges in doing so, but I believe we should start with a shared version.

Do you ask because you already now foresee a need to customise them?

**Comment by tucotuco** [comment]
I expect that there will arise the need to customize them, but not because
we have one at this moment. I agree that the best starting point is to have
good shared versions. I think we are interested in providing these. Should
we do that through a pull request on this repo?

**Comment by MortenHofft** [comment]
This question seem to be the same as https://github.com/gbif/hosted-portals/issues/60#issuecomment-827125356 ?

My primary concern with that is my worry that someone/you waste effort because we/I later decide to restructure something in the UI that make that help text unused. But that might be worrying too much. 

Secondly, then some texts are still hardcoded, so you might not be able to find everything in the translation files.

And lastly, the format of the translation file will likely change, but that won't influence any text.

You are welcome to do pull requests with text changes to [the project](https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/locales/en.js). Or just provide them here and I will copy them (if it becomes overwhelming I might back down on that approach and accept pull requests only).

**Comment by tucotuco** [comment]
I am in the process of amending commonFilters.js, getCommonSuggests.js, and locales/en.js There are three terms that aren't clear to me to what they refer. I don't see anything in the hosted portals to which they might refer. Can you tell me what they are suppose to be? They are:

[name](https://github.com/gbif/gbif-web/blob/b2ff47f6006e93c3c89f8def3db030e883548084/packages/react-components/src/utils/filterBuilder/commonFilters.js#L825)
[city](https://github.com/gbif/gbif-web/blob/b2ff47f6006e93c3c89f8def3db030e883548084/packages/react-components/src/utils/filterBuilder/commonFilters.js#L843)
[code](https://github.com/gbif/gbif-web/blob/b2ff47f6006e93c3c89f8def3db030e883548084/packages/react-components/src/utils/filterBuilder/commonFilters.js#L861)

**Comment by tucotuco** [comment]
I created a [pull request](https://github.com/gbif/gbif-web/pull/18) with English text for as many terms as I could identify.

**Comment by MortenHofft** [comment]
First of all - thank you for correcting all those texts!

> Can you tell me what they are suppose to be? They are:
name
city
code

The list of filters is used across search for publishers/datasets/occurrences/institutions/collections/literature

name, city and code are specific to institutions and collections. You can see it in use here https://react-components.gbif-staging.org/iframe.html?id=search-collectionsearch--example&args=&viewMode=story

**Comment by MortenHofft** [comment]
Thanks to @tucotuco I will close this issue. There is likely more placeholder values and mistaken hardcoded help texts lingering, but the large bulk is solved now.
