### ISSUE TITLE
Suggests generally do not work

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#135]
from @tucotuco

> you can't find the one you're looking for in the pop-up menu, which is a general serious issue not just for county

@tucotuco it would be useful if you spelled out the list of broken suggests (is it all? 2? 10? which?) ideally with some examples.

I'm aware that it is [an issue for GADM suggest](https://github.com/gbif/portal-feedback/issues/3044#issuecomment-804618844), but wasn't aware that it was a general problem. 

Thank you for your help

**Comment by tucotuco** [comment]
I have added a broader, yet detailed https://github.com/gbif/hosted-portals/issues/136 covering text searches. Will that suffice?

**Comment by MortenHofft** [comment]
Thanks. Yes that is much more useful - I might move it to another repo as it is not a ui issue as such, but more likely to have a better solution in the backend. That said the improvement could be a combination. But except the experiment with adding wildcard search for identifiedBy (which was added as a test for a demo), then it all applies to gbif.org as well, so I might move it there.
