### ISSUE TITLE
Wildcard search

### ISSUE THREAD

**Issue by tucotuco** [gbif/hosted-portals#136]
We have some observations about text searches within particular filters. There seems to be inconsistency in how they function (or don't). 

Ideally we would like to be able to make the most out of finding records using simple pattern matching within the fields where it makes sense. For example, I am interested in finding records where recordedBy is Oliver Payne Pearson (https://en.wikipedia.org/wiki/Oliver_Payne_Pearson). Without having a recordedByID for him, and without having had anyone do the tremendous amount of work required to assign his copious collections to an identifier, and without having had those identifiers matched to the Occurrences, how would one go about finding those Occurrences? Being able to use SQL-like patterns, with '%' or '*' and '?' within the recordedBy field would help a lot. 

The behavior of the identifiedBy field suggests that this is at least partially possible. In that field, the UI help text says, "Use * as a wild card". That seems to work ('Pearson*' returns results), except that the text box does not permit an '*' (nor '?') to be entered as the first character. For this and other fields we would like to be able to search for 'O*Pearson*', for example. In order to be truly useful, the search would also have to be case insensitive, so that the search above would find records with 'OP PEARSON' and 'Oliver Pearson'. Case insensitivity does seem to be in effect in the identifiedBy field.

The recordedBy field doesn't work the same as the identifiedBy field. Though probably much more frequently needed, this field's search capabilities are much more limited. This is likely because it is trying to do typeahead matching, which is broken in general (see https://github.com/gbif/hosted-portals/issues/130). There are numerous problems with this approach. One big one is that one can never see (and therefore can never select) all of the possible combinations of recordedBy that begin with 'Oliver P. Pearson' - they go beyond the list length and none are removed when added to the filter list.

Text match searches are immensely useful for a variety of fields, including (in addition to recordedBy and identifiedBy):

preparations
previousIdentifiocations
fieldNumber
samplingProtocol
higherGeography
waterbody
islandGroup
island
locality
georeferencedBy
higherClassification

In the case of waterbody, there appears to be only case-insensitive exact matching available. This exact matching extends to accented characters as well, so that 'Río de la Plata' gives distinct results from 'Rio de la Plata'. In geography in particular, a better matching pattern would be a combination of case-folding, NFKC unicode normalization, and diacritic simplification (see https://github.com/VertNet/bels/issues/2#issuecomment-761638717) on both content and input strings.

**Comment by MortenHofft** [comment]
Thanks - a lot of points here. So just briefly on one of them: wildcard search

I added it to identifiedBy to start a discussion and see if there was an interest in it. It seems there is.

It was added to `identifiedBy` as an experiment. Similar with negation (only available for `issues`) and existence (only available for `eventId` as far as I remember). That isn't to say we couldn't add it for more, but the performance cost need to be discussed first. Negations are expensive and so is wildcards. That is also the reason I disabled `*` as a first character.

**Comment by tucotuco** [comment]
OK, great. This gives me great hope. Given the expectations of the monster
community we created, we vote for capabilities over performance.

**Comment by MortenHofft** [comment]
So the constraint is the intersection of Elastic search and the download API.

This are the constraints from ElasticSearch which data is indexed in
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

> ?, which matches any single character
> *, which can match zero or more characters, including an empty one
> 
> Avoid beginning patterns with * or ?. This can increase the iterations needed to find matching terms and slow search performance.

For Downloads this are the options
https://www.gbif.org/developer/occurrence#predicates
See also https://github.com/gbif/occurrence/issues/245

Since that issue isn't resolved it is hard to tell for sure, but my guess would be that we could have `*` to match one or more characters (though we might have to disable it as the beginning of the word for performance reasons).

**Comment by MortenHofft** [comment]
@jholetschek and @tucotuco and @langeveldNMR 

I am experimenting with another way to query text fields than using the standard suggest we use on GBIF.org. You have all 3 identified good reasons to explore alternatives.

**Pros and cons of existing suggest** 
* pro: it is fast
* pro: you are forced to look at the individual values and hence know what you will get
* con: it is hard to find what you are looking for
* con: it will suggest things not in your data scope.

**Pros and cons of existing wildcard search** 
Pure wildcard search as we have for identifiedBy on the hosted portals. [See example](https://hp-theme.gbif-staging.org/data/?filter=eyJtdXN0Ijp7ImlkZW50aWZpZWRCeSI6WyJ3aWxsaW5nKiJdfX0%3D)
* pro: you can find way more items than with simple suggest
* con: You are shooting blindly
* con: You do not know what you get. 95% might be the name you are looking for, but there might well be noise in there. That dilutes citation tracking and adds noise to the result.

I've tried to get the best of 2 worlds with below attempts
**Attempt 1: Use distinct values as suggest**
https://hp-theme.gbif-uat.org/data/?filter=eyJtdXN0Ijp7InJlY29yZGVkQnkiOlsid2lsbGluZ3MsaC5qLiJdfX0%3D

* pro: it only suggest values that is in your portals scope
* pro: it supports wildcards (* and ?)
* pro: you are forced to look at the individual values and hence know what you will get
* con: it is cumbersome to select many values
* con: it is slower

<img width="370" alt="Screenshot 2021-05-12 at 16 35 54" src="https://user-images.githubusercontent.com/6759267/117994512-e66b4280-b340-11eb-820c-5a81532e1550.png">


**Attempt 2: same as 1, but with a different layout**
https://react-components.gbif-uat.org/iframe.html?id=utils-filters-from-config--example&args=&viewMode=story

* pro: it only suggest values that is in your portals scope
* pro: it supports wildcards (* and ?)
* pro: you are forced to look at the individual values and hence know what you will get
* pro: Simply to select many values
* con: it is slower
* con: less intuitive to use I suspect

<img width="361" alt="Screenshot 2021-05-12 at 16 34 09" src="https://user-images.githubusercontent.com/6759267/117994481-dfdccb00-b340-11eb-9202-75f4045c4c70.png">

**Comment by jholetschek** [comment]
Hi Morten,

thanks for taking the time do dive into this! In our small play-around-and-give-feedback round the recordedBy filter there have been strong opinions on the recordedBy filter. It is one of the key items to find records for botanists, and the missing free text search feature on collectors of the GBIF portals has been one reason in the past to create our own portals - like the one we now plan to replace by the hosted portal. If we lose search functionality in doing this, the new portal would have difficulties in getting user acceptance, even if it has a lot more features than the old one. If we break the way they are used to find their data, they won't use it.

As for the collectors, there are often so many variations that showing a list to select values from is not even necessary. Take Friedrich Wilhelm Heinrich Alexander von Humboldt as an example - there are just too many ways to abbreviate. To make things worse, he was usually accomanied with Bonpland. I just had a look and found 362 distinct recordedBy values in the GBIF index containing Humboldt, about 300 of them seem to be true positives. And I think it's not necessary. People don't mind some false hits, they will just ignore it or add another filter - not missing something is more important.

So for recordedBy and identifiedBy I tend to say that the exisiting solution for identifiedBy would do the job. Regarding the second one of your attempts: Is the list suggestion list complete? If it is and if there would be a "select all" button, it would be a good way to combine both worlds in my opinion.

In general I agree with what John wrote - capabilities over performance. Users are a bit spoilt by Google, but they're also happy to be able to find what they're looking for.

**Comment by MortenHofft** [comment]
Thank you Jörg

The Humboldt example is good in that it shows the problem well
 
* It perfectly outlines the issue with a simply suggest as we know it from GBIF.org.
* It is also far from ideal to manually click 300 checkboxes (out of the 362 distinct values for `*Humboldt*`) as in my attempt above.
* It also shows that although 300/362 names are probably correctly the Humboldt we are looking for, then 25% of the records are not by Humboldt. And so the search result would be very wrong/misleading. So simply searching with a wildcard and trusting it is clearly also a bad idea.

I like the idea of showing the individual options along with a "just-let-me-use-the-wildcard-already"-option. Then at least we have highlighted the problem of doing so and given the user an easy (in most cases) way to select vetted names, which I really believe is to be preferred.

**Comment by jholetschek** [comment]
Combining both sounds like a good idea - showing the pop-up and giving the "just-let-me-use-the-wildcard-already" option.
Somehow users should know why they get the results, so they can decide to go the quick way (and get some false hits) or to check items in the list, if they want to be precise.

**Comment by MortenHofft** [comment]
@tucotuco I looked at the fields you mention above. Most of them aren't supported in API v1 and hence not in downloads. Most of them aren't indexed either. So it isn't something that we can add to the hosted portals either. If you believe they should be available in search and download, then please leave a comment on [this issue](https://github.com/gbif/pipelines/issues/515) with which fields you believe are missing.

I do not see any support for these fields:

* preparations
* previousIdentifiocations
* fieldNumber
* higherGeography
* islandGroup
* island
* georeferencedBy
* higherClassification

**Comment by MortenHofft** [comment]
The new filter is deployed and available on your respective portals. I'm not entirely satisfied with the user experience of it I must admit, but not sure how to improve it either (an explicit search button would help). But it is better and more powerful than what we had. I will leave it for now.

This is the state of it - you can stick with the wildcard query or you can select the individual distinct values. That is informative either way.

<img width="328" alt="Screenshot 2021-05-19 at 22 18 12" src="https://user-images.githubusercontent.com/6759267/118878791-3e311d00-b8f0-11eb-8ab0-a869bea4edb1.png">

**Comment by tucotuco** [comment]
@MortenHofft I have been playing with the solution for wildcard searches and I think it still doesn't fill the need. It is a little difficult to understand why, because the way you describe the solution and from what you show, the intention is all there, but it just isn't working correctly, or at least not how I would expect. 
Your example above of *O*Pearson* is exactly the kind of pattern we would like support for (what the power users expect so that none of the records of interest are lost - even if they have to sort through the results to discard false positives), but it doesn't seem to work completely. Here is what I mean. If I click on the Apply button with the interface just as you show it above, no filter is applied. I still get all records in the portal. Though Oliver was prolific in his collecting, he wasn't involved in every vertebrate ever captured. ;-) 
I also tried to click on the Apply button without having expanded the selection with the Show suggestions slider, with the same result. It seems like the only way for a filter to be invoked is with checked boxes from the suggestions list. That's not viable for reasons already discussed in other comments. The most important thing we have identified as a need is for that pattern *O*Pearson* to make that filter, the suggestions are just icing on the cake to facilitate exploration for those so inclined.
This is even more true for the locality field, in which the number of variations is often far greater than that for recordedBy. It is an important use case to be able to retrieve every record that mentions a named place, and the other text around that named place in the locality description is almost always irrelevant to the search.
If I am just doing something wrong, please show me how silly I am.

**Comment by MortenHofft** [comment]
This sounds like a usability issue to me? Searching for the pattern is possible. It is the first option in above example. You just have to select it.
https://hp-vertnet-plus.gbif-staging.org/data?filter=eyJtdXN0Ijp7InJlY29yZGVkQnkiOlt7InR5cGUiOiJsaWtlIiwidmFsdWUiOiIqTypQZWFyc29uKiJ9XX19&from=0

**Comment by tucotuco** [comment]
OK, yes, I see it and yes, I feel silly. The Show suggestions slider bar is what led me astray. I expected my entry in the text box to be sufficient to execute the search and the slider bar to show me actual values to select and filter on. I did not expect to see my pattern in that suggestion list nor have to select it. Because I didn't expect it, I didn't see it.

The user experience does seem odd to me, but I am ecstatic that the hoped-for queries can be done.

**Comment by tucotuco** [comment]
Thinking more about it, here is the behavior I would implement. The Apply button executes the search with the pattern if the suggestion list is not open. Opening the suggestion list with a pattern entered would show all distinct options (and not the pattern) and all of the options would be selected. If the suggestion list is open and the Apply button is clicked, all checked suggestions would be used (OR'd) in the filter.  I realize the number of possible selections makes the automatic selection of all of them problematic.

**Comment by MortenHofft** [comment]
Thank you thinking about it. And as mentioned I'm not too happy with the UI either, I had a feeling it would be confusing. I'll give it another round soon. I'm not sure I can implement above suggestion in a good way, but I will give it some thought.

**Comment by jholetschek** [comment]
I also tried the pattern search and +1 to what John wrote.

If that's difficult, it would be at least very helpful to bring out the "search for pattern" item in the list optically. Even though there is a separator, it just looks like one of the suggestion entries. Maybe it's possible to turn it into a "search for pattern" button to make it obvious it's doing something else than the entries below?

**Comment by MortenHofft** [comment]
It would be great if someone could draw the full flow. Ideally as it should look, but even just pencil on a paper would be useful.

These are the criteria as I see it:
* It cannot be an autocomplete (that change as you type) as that wouldn't perform well.
* It should behave/look similar to the other filters (unless we want to rewrite them all).
* It should be able to handle multiple queries (imagine a [filter with 3 values](https://hp-theme.gbif-staging.org/data/?filter=eyJtdXN0Ijp7InJlY29yZGVkQnkiOlt7InR5cGUiOiJsaWtlIiwidmFsdWUiOiIqcm9iZXJ0KiJ9LCJkYW5pZWwgaC4gamFuemVuOyBoYXlhdGEiLCJkYW5pZWwgc3RlZW4iXX19&from=0)) - e.g. how does the user deselect an option and add a new one, but keeps the remaining two.
* It has to support both pattern and exact values (and the possible suggestions should be listed for the user to learn/evaluate)

**Comment by jholetschek** [comment]
Hi Morten,

here is how I would imagine it:

When "show suggestions" are off (which is the default), there is just the text field and the hint on the placeholders. The button would read "Apply pattern" and would do the same as 1. turning suggestions on, 2. selecting "search for the pattern", and 3. hitting "Apply":

![pattern](https://user-images.githubusercontent.com/11058397/129367802-2a21db72-8eb8-4dfb-a889-af1c39a6eb37.png)

When suggestions are turned on, you get the list, but without the item "search for pattern". Ideally, there would be a "tick/untick all" link to allow selecting all and then unselecting unwanted items.

![suggestions](https://user-images.githubusercontent.com/11058397/129368041-b3082557-4660-4113-ae20-dd26da333572.png)

Hope it's clear what I mean. I'll be away next week, but back on August 23rd.

**Comment by tucotuco** [comment]
I agree with @jholetschek . That's exactly how I would make it work in every detail.

**Comment by MortenHofft** [comment]
Thank you! I've tried to apply it in this example and find that we still need to solve some details:

![wildcard example](https://user-images.githubusercontent.com/6759267/129531256-fae4a174-8911-4c70-9e00-ebc0b81e1e2c.jpg)

I have 3 values selected already. I open it to deselect an option and add 2 patterns.

Does the button label change? How do I add multiple patterns? How about consistency, other filters do not apply until it has been added as an option (the checkbox with text).

**Comment by MortenHofft** [comment]
I've changed things a tad. It still isn't exactly as I'd like it, but I think it is an improvement. I really just removed the apply button when nothing is selected (same as we do for other filters). Added an explicit search button. And finally added a bit of spacing to the pattern option to make it stand out just a bit more.

![Screenshot 2021-08-16 at 11 49 56](https://user-images.githubusercontent.com/6759267/129545274-8bb9bedf-0e91-449e-80f8-e37a83c5b216.png)

**Comment by tucotuco** [comment]
This is looking pretty good. There are some things that I would expect to work a little differently, but the needed functionality is getting there. One thing that I would expect is that clicking on the search button would simply run the query and close the dialog rather than opening the list. I would expect the list to open only when asked to with the Show suggestions slider. That isn't essential though, given that the results can be obtained in a fairly straightforward way, albeit with more clicks and potential for confusion.

In the current implementation the Apply button appears when the list is open after selecting anything. That is fine, but the Apply button doesn't go away when everything is deselected. It can still be clicked on to run the query, but there is no filter in place and that could be confusing.  Another UI option could be to have the Apply button there always, but enabled or disabled depending on selection state.

Apparently the search can not normalize accented and other extended characters to simplified canonical forms (e.g., o for ó). This is not obvious without playing around, and it is extremely important. A simple solution would be to add something like "Searches are case insensitive, but every letter is distinct, so, to find records with Rio or Río, for example, you can use the pattern '*r?o*'." to the comments where it says "You can search using * (wildcard) and ? (single letter wildcard)".

Nice job. I am getting happier with every iteration.

**Comment by jholetschek** [comment]
I agree with what John wrote in every detail... this is really very good!

One tiny thing (sorry for being nit-picky, I'm just anticipating user feedback): Upon clicking "load more suggestions" - would it be possible for the list not to scroll up to the beginning?

**Comment by MortenHofft** [comment]
> Upon clicking "load more suggestions" - would it be possible for the list not to scroll up to the beginning?

Makes sense. The existing entries are now kept when loading and hence is the scroll position.

**Comment by albenson-usgs** [comment]
Would it be possible to have this presented at the next hosted portals meeting? This is a long thread and it's difficult to understand exactly what was implemented. A quick walkthrough would be helpful for me at least.

**Comment by MortenHofft** [comment]
Sure we can do that. We also touched briefly on it in our last meeting. If you go to the recording sent out August 9 and go to the video 20m47s, then you will see me attempting to explain how it works.

* The way we search recordedBy on GBIF.org is simply a suggest based on what values exists (in all occurrences). And the suggest match the first characters. 
* Tucotuco and others expressed a desire to have wildcard search instead. 
* I'm reluctant to simply do wildcard search leaving users blind to what results they get back (I have no idea what noise is included in my pattern)
* Instead we tried to get the best of the 2 by allowing users to enter a search pattern (using wildcards) and then show all the distinct values that match that pattern. The user can then choose to
  * Use the pattern (and include all values that match)
  * Or select individual values that match the pattern.

This has the benefit that you get more relevant suggestions (as seen in below screenshot you get 3 suggestions on GBIF.org whereas this approach provides 10 correct suggestions and 1 wrong. And you can use the pattern if you choose to (and include the presumably "wrong" occurrences by `Christina Shobernd`)

<img width="346" alt="Screenshot 2021-09-08 at 07 28 36" src="https://user-images.githubusercontent.com/6759267/132452715-375d8557-43fa-4fb6-b1c8-43d6f389599c.png">
<img width="383" alt="Screenshot 2021-09-08 at 07 37 03" src="https://user-images.githubusercontent.com/6759267/132452719-fb387556-73e6-44ab-991e-5bfb13c14f76.png">

In below example it is more extreme example where just using the pattern would include a lot of noise
<img width="334" alt="Screenshot 2021-09-08 at 07 46 36" src="https://user-images.githubusercontent.com/6759267/132453416-a089bf30-2b55-4e9d-9978-60097667e2b8.png">

The best way to understand what was implemented is to look at the filters. E.g. `Recorded by`
