### ISSUE TITLE
Organism count-related filters

### ISSUE THREAD

**Issue by tucotuco** [gbif/hosted-portals#137]
We see that there is a filter for organismQuantity, but there isn't one for individualCount. Looking at a GBIF snapshot from 2021-02-12, organismQuantity was populated in 3.1% of Occurrence records, while individualCount was populated in 59.0% of Occurrence records. In Darwin Core, individualCount is expected to be a number (of individuals), and therefore easy to search on, whereas organismQuantity might contain string values and require organismQuantityType in order to understand those values.

It's not clear if the organismQuantity acts in the hosted portals as if it has numeric data type. The suggestion text says "Range or single value", but it is possible to enter real values that are strings in the search box. However, entering a string that exists in the underlying data ('R', for example - there were 262475 Occurrences with this value in the 2021-01-12 snapshot) seems to fail to return results (as opposed to zero results - see https://hp-theme.gbif-staging.org/data/?filter=eyJtdXN0Ijp7Im9yZ2FuaXNtUXVhbnRpdHkiOlt7InR5cGUiOiJlcXVhbHMiLCJ2YWx1ZSI6IlIifV19fQ%3D%3D).

Related: What is the "Relative organism quantity" filter? It also says "Range or single value" in the suggestion text of the search box.

**Comment by MortenHofft** [comment]
**organismQuantity etc**
I haven't been involved in the process so I cannot elaborate much, but as far as I can see the discussion for adding these took place here https://github.com/gbif/pipelines/issues/244

>It's not clear if the organismQuantity acts in the **hosted portals** as if it has numeric data type

The behaviour is the same as gbif.org - I suggest you create an issue on https://github.com/gbif/portal-feedback/issues/new if you believe this API addition is problematic.

**individualCount**
individualCount is not documented as part of APIv1 - but I do see it in the index, but not in the api
http://api.gbif.org/v1/occurrence/search?limit=0&individualCount=2
You can [create an issue for it](https://github.com/gbif/pipelines/issues/new)
