### ISSUE TITLE
Hosting organization search fails

### ISSUE THREAD

**Issue by tucotuco** [gbif/hosted-portals#138]
We have tried to do a search for Hosting organization "VertNet". The text box for the Hosting organization filter shows and allows us to select "VertNet", but the results fail to return (as opposed to zero results). 

![image](https://user-images.githubusercontent.com/462827/116142280-1b746580-a6b0-11eb-8037-c71cde0e3296.png)

**Comment by MortenHofft** [comment]
Thank you 
The API previously took its query name directly from the data index, but I renamed it to match API v1. I didn't update the UI accordingly for all values.

closed by https://github.com/gbif/gbif-web/commit/8efca5c38980b4910352badaeb56a000fb35b1c6
