### ISSUE TITLE
image load speed

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#139]
The theme has changed to use webp via the Thumbor. This should provides much smaller images and hence better load times. But in reality they are much slower:

* generating them is apparently slow
* they are not cached (at least not for very long - it feels like the cache is purged many times daily)

Could we extend the caching? I still think the idea is good, but as it stands I would rather go back to jpg or whatever format and size the images was uploaded in.

**Comment by MattBlissett** [comment]
I've adjusted the Thumbor caching to keep larger images — the previous assumption was the largest images would only be from occurrences, which would not usually be worth caching for a long time.

Let me know later next week if there's any improvement.
