### ISSUE TITLE
add no-index header

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#14]
It would be nice to exclude robots entirely from the staging site. 
Using `robots.txt` do not mean being excluded from search. You need to add either http headers or - for html - a meta tag.
It would be nice to exclude everything (including pdfs, images etc) from the staging site. 

@MattBlissett  Should we add `X-Robots-Tag: noindex` http headers to everything served from the staging sites?

**Comment by MattBlissett** [comment]
Done, for all *.gbif-uat.org and *.gbif-staging.org static sites.
