### ISSUE TITLE
Warning message about rexml

### ISSUE THREAD

**Issue by dbloom** [gbif/hosted-portals#140]
Receiving notifcations about a vulnerability in Ruby.  Is this something that I need to take care of or is it something that will be addressed via update or otherwise by GBIF?

Full notification:
https://github.com/gbif/hp-vertnet-plus/security/dependabot/Gemfile.lock/rexml/open

**Comment by MortenHofft** [comment]
We will look at it and most likely update all sites. You are also welcome to do so for your own site.

**Comment by MortenHofft** [comment]
The dependency was updated
