### ISSUE TITLE
data exploration | Relative organism quantity filters

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#143]
There is a filter called 'Relative organism quantity', what is it for? it is a merge of organismQuntity and type?
We tried to use to find out but it doues not return any results.

It also has a missing descripton.
<img width="349" alt="Captura de Pantalla 2021-05-01 a la(s) 9 05 50 a  m" src="https://user-images.githubusercontent.com/5700527/116784989-d14b0580-aa5c-11eb-8d72-fd0db81d5286.png">

**Comment by tucotuco** [comment]
Also asked in https://github.com/gbif/hosted-portals/issues/137.

**Comment by MortenHofft** [comment]
Aside from being in need of an explanation it doesn't really work either it seems.

**Comment by MortenHofft** [comment]
I've reviewed the behaviour. The filter work as intended. But a better explanation would probably be useful. Remember that it is possible to remove this filter from your individual sites. Also see https://github.com/gbif/portal-feedback/issues/3405 where the merits and failures of this filter is better discussed
