### ISSUE TITLE
deploy base theme

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#15]
I believe it would be useful to have the base theme on staging along with the remaining hosted portals. It is useful to have a place to show the various layouts and options in a visual manner. It could be done using `hp-demo-fungi` but it feels a bit convoluted, since they are being developed in the base theme anyway.

Currently the base theme is hosted on netlify

**Comment by MattBlissett** [comment]
It's now at https://hp-theme.gbif-staging.org/.  If it's released through GitHub, it will be deployed to https://hp-theme.gbif.org/

**Comment by MortenHofft** [comment]
the site isn't working anymore. https://hp-theme.gbif-staging.org/styling/ is a server 404 page (not the styling existing page it should be) and not the custom 404 page either.
The data page isn't working. Neither with or without the trailing slash

**Comment by MortenHofft** [comment]
It seems the cache isn't cleared upon deployment?

**Comment by MattBlissett** [comment]
Is it just the browser cache? I saw the same effect, but refresh fixed it.  

The browser caching is just the default; we don't have `Cache-Control: must-revalidate` or similar.

**Comment by MortenHofft** [comment]
I agree - I must have fumbled with the cache. I didn't see it earlier today.

**Comment by MortenHofft** [comment]
404 pages doesn't work for the base theme

**Comment by MattBlissett** [comment]
Sorry, I missed this.

The theme site did not include the HP configuration.
