### ISSUE TITLE
Occurrence details: The field description in the detailed view of an image

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/hosted-portals#154]
In the detailed view of an image (e.g. this record https://hp-nhm-rotterdam.gbif-staging.org/data?entity=2570097743&filter=eyJtdXN0Ijp7InRheG9uS2V5IjpbMjMwMDQ3OV19fQ%3D%3D, after clicking on the image), the field 'description' that is included in the extension file multimedia is not displayed (compare same record on GBIF: https://www.gbif.org/occurrence/2570097743). Could this field be included in the hosted portal view?

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/gbif-web/commit/d3c1505acabd9a20efb6069232515d7806e6404e
