### ISSUE TITLE
Data download is empty

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/hosted-portals#162]
I just tested out the new download capability but the [resulting download](https://www.gbif.org/occurrence/download/0284827-200613084148143) was empty. What I did:
1. Went to the BISON hosted portal https://hp-bison.gbif-staging.org/
2. Clicked "Scientific Name", started typing _Bison bison_ and selected the relevant scientific name, result = 11821 occurrences
3. Clicked "Download"
4. Signed in and followed prompts to create the Darwin Archive download.

**Comment by MortenHofft** [comment]
Oh indeed. The negation is lost. So it asks for bisons in the US etc that HAS the issue `Country coordinate mismatch`. That is a bug.
