### ISSUE TITLE
Generating multiple files from the same markdown page

### ISSUE THREAD

**Issue by frafra** [gbif/hosted-portals#167]
Hi,
we would like to generate multiple files from the same markdown page, but it seems that Jekyll does not support that. Do you have any suggestion on how to do that?

Here is what we tried and the reasons behind this need: https://github.com/gbif/hp-living-norway/issues/11

Thank you :)

**Comment by MortenHofft** [comment]
I'm afraid I do not know up front how to do this either, but the [generators](https://jekyllrb.com/docs/plugins/generators/) you mention sounds right to me.

Reading issue gbif/hp-living-norway#11 I'm not sure that it is the correct approach either though. But I'm not entirely sure what the goal is - especially as the terms `collections` and `projects` are already in use in the GBIF APIs, but I suspect you mean something else.

**Comment by frafra** [comment]
Hi Morten :)

From our limited understanding, it is not possible to get all the datasets belonging to a project, as `/dataset/suggest` returns a maximum of 20 results. `collections` seem to be a group of institution and people, not datasets, so I would say that we are looking on how to define collections of datasets. We are relying on regular tags at the moment.

**Comment by MortenHofft** [comment]
If we mean the same thing with `project` then you can get all dataset belonging to a project by filtering by the projectId and page over those results

https://api.gbif.org/v1/dataset/search?projectId=GRIIS
https://api.gbif.org/v1/dataset/search?projectId=GRIIS&size=100&offset=100

`/dataset/suggest` is intended for autocompletes - as in the user types `ebi` and the suggest returns an array of datasets that are typically shown in a dropdown.

**Comment by MortenHofft** [comment]
And you are right - in GBIF terminology a collection is best understood as a museum collection. E.g. a herbarium from a specific institution. So it isn't a collection of datasets as such.

**Comment by frafra** [comment]
Thank you, Morten. We did not tought it was possible, as `projectId` is not mentioned as possible parameter for the `/dataset/search` endpoint :)

**Comment by MortenHofft** [comment]
That is a mistake. I have added that. Thank you

**Comment by MortenHofft** [comment]
@frafra I'm closing this issue as I believe you have already identified the correct approach - namely generators.
Lets continue the discussion about the Living Norway specific issue as gbif/hp-living-norway#11

Let me know if you believe this should be reopened.
