### ISSUE TITLE
Establish the NZ portal

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hosted-portals#168]
Set up the github repository and necessary environments for the national New Zealand portal to be named "GBIF New Zealand"

**Comment by AaronWilton** [comment]
please include philipedgar  (github handle)

**Comment by MattBlissett** [comment]
The source code for the portal is ready: https://github.com/gbif/hp-new-zealand and it's deploying to https://hp-new-zealand.gbif-staging.org/ .  Aaron and Philip have invites to this repository, and can add other GitHub users as required.

**Comment by MattBlissett** [comment]
Hi @AaronWilton,

In case you've missed the invite to the hp-new-zealand repository, you can see it at https://github.com/gbif/hp-new-zealand/invitations

**Comment by AaronWilton** [comment]
Hi @MattBlissett  - sorry yes, missed the invite.  Can you please reset -- it has expired.
thanks

**Comment by MattBlissett** [comment]
I have resent it, so you should have an email, or just click the link above.
