### ISSUE TITLE
Data page: allowing user to select columns

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/hosted-portals#171]
Would it be possible to have an option where the user can select which columns are displayed after making a query in the data page? I mean the columns that I put in a red rectangle in the attached file.
![This one please](https://user-images.githubusercontent.com/69208596/128725726-7f592b7e-52d9-4118-9eb1-a964fcb4f0d8.jpg)
 For example, it could be useful for a user to be able to add 'Catalog number' to the displayed table, or to remove 'Dataset'.

**Comment by tucotuco** [comment]
Is this somehow different from #120

**Comment by langeveldNMR** [comment]
I think that issue was interpreted as a request to make the highlighted search options (green boxes in the screenshot) customizable by us ('builders' of the portals). I am however requesting the possibility for end users (people using the portals once they are live) to be able to select which columns they see in the red box in the screenshot after they have searched the dataset. E.g. when they get 10 results, it would be convenient to make the catalog number visible in that overview, so they can copy/paste those and send a curator an email requesting access to those specimens.

**Comment by MortenHofft** [comment]
I too understand this as the same as https://github.com/gbif/hosted-portals/issues/120
If there is a difference then I need a bit more explanation please. I read both as adding functionality similar to below screenshot from GBIF.org

<img width="1253" alt="Screenshot 2021-08-10 at 12 40 48" src="https://user-images.githubusercontent.com/6759267/128854520-1c42bc16-1d84-46c3-a363-8e9aae5c8e8e.png">
