### ISSUE TITLE
Translation | Dowload email

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#179]
As dowloads redirect to GBIF main page, and the download email is send directly by GBIF we should start to think about the translation of the Dowload email or other suitable alternatives to get this information on the user lenguage. Maybe by detecting from wich portal the request was sent (but many portals have multiple lenguages)

<img width="1343" alt="Captura de Pantalla 2021-08-31 a la(s) 8 37 33 a  m" src="https://user-images.githubusercontent.com/5700527/131513813-b2d612c6-9b6a-4eab-867a-9d741658693c.png">

**Comment by MortenHofft** [comment]
Your timing is good. I believe this work is already implemented and translation taking place
https://crowdin.com/project/gbif-registry/content/files

But we want to make sure the link to GBIF.org redirects to the correct language

**Comment by camiplata** [comment]
Great, we have done the translation on crowdin we will make some test this week around the redirection.

**Comment by camiplata** [comment]
I just checked and if the GBIF user accout is set in X language the dowload email is recieved in that x language. But if the user account has not language defined even by doing the dowload  from a portal in x language the email is recieved in english. I know you are working on that, the comment is only to let you know the behavior we noticed by doing trials.

**Comment by MortenHofft** [comment]
If a user creates an account using the "spanish site" `gbif.org/es`, then the user account automatically has the preferred language set to Spanish. 

If the account was created before we introduced this, then the default language is english.

A user can at any time change their preferred language in profile settings
https://www.gbif-uat.org/es/user/profile

If the sent mails aren't sent in the correct language, then it sounds like a bug we should create an issue for

**Comment by MortenHofft** [comment]
The hosted portal now redirects to the corresponding language version on GBIF.org.
