### ISSUE TITLE
Home Page - Logo is too small

### ISSUE THREAD

**Issue by rondlg** [gbif/hosted-portals#18]
Hi,

we can't seem to resize the logo in the top left corner of the site pages (eg https://hp-north-america.gbif-staging.org/) to a sensible size. Is that set in css or is it something we can modify/tweak?

![image](https://user-images.githubusercontent.com/702709/108246332-ef1ff400-7116-11eb-9efa-0d998b29dbf4.png)

Sharon

**Comment by kcopas** [comment]
Leaving aside ths specific point here @rondlg, in your case, we have branding guidelines for representing regions. Apologies—@timrobertson100 flagged this for me some days ago. 

The format of the regional logo is simpler and (as a result) probably more legible at smaller scale. Goes something like:

![GBIF-2015-NA@0 5x](https://user-images.githubusercontent.com/12379236/108331170-c8bd8f80-71ce-11eb-8d3b-6cd17f783aae.png)

Cc: @MattBlissett @MortenHofft

**Comment by MortenHofft** [comment]
It isn't exactly well documented, but yes it is possible.
https://hp-base-theme.gbif-staging.org/markdown#styling-content

The theme is build on [Bulma](https://bulma.io/), so you can change the variables to your liking as well as add custom css. 
I've [changed the logo size](https://github.com/gbif/hp-north-america/commit/39a94cdd993439a4d3224b74a3ed3f4b1b7b456a), but in my opinion the one allotted above does not work well in this context. It is off balance. And giving it an offset does not help I find.

Logo centered
<img width="267" alt="Screenshot 2021-02-18 at 14 55 25" src="https://user-images.githubusercontent.com/6759267/108367192-7ba2e300-71f9-11eb-9ced-b4102c194f69.png">

Logo with offset
<img width="346" alt="Screenshot 2021-02-18 at 14 55 10" src="https://user-images.githubusercontent.com/6759267/108367188-7a71b600-71f9-11eb-9ede-8757a80bc8a7.png">
