### ISSUE TITLE
Request to translate  filters help texts

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#185]
@MortenHofft  We have been translating a lot of the recommended folders but I still have not come across with the translation of the search filters help texts, could you please let me know were can I find them so I can prioritise this texts
<img width="582" alt="Captura de Pantalla 2021-09-27 a la(s) 8 43 21 a  m" src="https://user-images.githubusercontent.com/5700527/134937419-82703fae-5829-4a9e-95b2-de6371c08aec.png">
.

**Comment by MortenHofft** [comment]
It is probably one of those that haven't been added to the translation file yet. Thank you

**Comment by camiplata** [comment]
I'll be checking the crowdin project to translate those as soon as they are available.  BTW I think the filter names are also missing on crowdin as I have nof found "Administrative Area" or  "Issues an flags" for translation.

**Comment by MortenHofft** [comment]
They are ready for translation (on my end), but are awaiting approval by the GBIF comms team before they can be translated.
The flow is: 
* I write my best attempt in danish-english.
* That is the source for translating to proper UN english (GBIF communication handles this step in Crowdin)
* And that UN english then becomes the source for all other translations

**Comment by camiplata** [comment]
Do you know if this has been added to translation already?

**Comment by MortenHofft** [comment]
https://crowdin.com/translate/gbif-portal/705/en-es?filter=basic&value=3#q=wildcard

it has been available since October :) https://github.com/gbif/gbif-web/pull/76

**Comment by camiplata** [comment]
I have checked the link but it appers empty, neither the FILTERSUPPORT.JSON file shows the wildcar string, maybe it is hiden for translators?

<img width="993" alt="Captura de Pantalla 2022-02-24 a la(s) 8 14 49 a  m" src="https://user-images.githubusercontent.com/5700527/155531049-de90e2de-a75d-4085-9e11-40cb96675a4e.png">

<img width="1030" alt="Captura de Pantalla 2022-02-24 a la(s) 8 14 59 a  m" src="https://user-images.githubusercontent.com/5700527/155531047-142364cb-9d8f-4e65-9ddc-b9d3564cdfea.png">

**Comment by MortenHofft** [comment]
You are completely right - it is hidden. I do not know much about Crowdin - @dnoesgaard can probably answer this. I do not see why it should be

**Comment by dnoesgaard** [comment]
I rarely interact with the gbif-portal project but only gbif-portal-en for the English "translations". I have no idea why these translations would be hidden. 

I get the feeling that some if not all of these are all relatively recent additions, e.g.
![Screenshot 2022-02-24 at 17 36 11](https://user-images.githubusercontent.com/21358085/155567353-e1e20ff5-bf81-4477-bd17-356d200c0f21.png)

I wonder if new translations are hidden by default?

**Comment by MortenHofft** [comment]
Njah, "Connect to facebook" has been there for years. It seems kind of random. Shouldn't we just unhide them all? 
It is a bit annoying though if duplicate strings are then unhidden, but better that than hidding terms that shouldn't be

**Comment by dnoesgaard** [comment]
I'm fine with unhiding them, but it would also be nice to figure out why they were hidden in the first place...

**Comment by camiplata** [comment]
Thanks @MortenHofft @dnoesgaard  I made the translation for the wildcard. I'll be checking again once the mistery of the hidden strings is resolved.

**Comment by MortenHofft** [comment]
Could it be a bug with the duplicates settings in Crowdin? I think it might have been set to hiding duplicates in the past. It isn't the setting anymore, but perhaps the fields remain hidden? It is a but unlikely, but my best guess currently

**Comment by MortenHofft** [comment]
I've looked briefly. They all seem fine to unhide except for the MIXS ones which seems like a misunderstanding to begin with. How is anyone expected to translate `num_replicons` - it isn't english to begin with, but an enum of a sort. But that is an issue of its own. I will keep those hidden
