### ISSUE TITLE
Add columns "type status" and "record number" to table view

### ISSUE THREAD

**Issue by jholetschek** [gbif/hosted-portals#198]
For botanical specimen collections, type status and record number (aka collector number) are important fields. It would be nice if they could be added to the table view.

**Comment by MortenHofft** [comment]
Thanks @jholetschek I've added these options. But haven't updated your configuration as I didn't know the preferred order.

Changing https://github.com/gbif/hp-herbarium-germany/blob/master/_includes/js/config.js#L10
`defaultTableColumns: ['features', 'typeStatus', 'recordNumber', 'country', 'coordinates', 'year', 'recordedBy', 'dataset', 'publisher', 'catalogNumber']`
