### ISSUE TITLE
Data Page - Tab order

### ISSUE THREAD

**Issue by rondlg** [gbif/hosted-portals#20]
Hi,

On this page: https://hp-north-america.gbif-staging.org/data?view=dataset

Is there a way for us to alter the order of the tabs? For example switch the map tab to the 1st position?

Thanks

Sharon

**Comment by jenningsdt** [comment]
Tangentially related: in `navigation.yml`, I changed the `href` for the Data menu item to `/data?view=map` and now the portal displays the map by default and zooms in a little better.

**Comment by MortenHofft** [comment]
It isn't possible to configure the widget much yet. The focus currently is really to support the content part. But I fully agree that it should be possible to configure which tabs and in which order.

**Comment by rondlg** [comment]
Thanks for the update. 

We'll leave this in the "enhancements to request" bucket for now then.

**Comment by MortenHofft** [comment]
See [docs](https://hp-theme.gbif-staging.org/data-exploration-config#occurrence-search-tabs) for instructions.

```
var siteConfig = {
  rootPredicate: ...,
  occurrenceSearchTabs: ['MAP', 'TABLE', 'GALLERY', 'DATASETS'] // order and subset
```

**Comment by MortenHofft** [comment]
@rondlg I've put the [map tab first](https://github.com/gbif/hp-north-america/commit/7a691e9dbb8c956846c58465a89fd28d39507a86). If it was more a theoretical example, then i've made a mess

**Comment by MortenHofft** [comment]
important for those that have used the urls to link to specific tabs: all existing links should use the new enum casing
