### ISSUE TITLE
Occurrence details header shows "1 January 1970" for empty gathering dates

### ISSUE THREAD

**Issue by jholetschek** [gbif/hosted-portals#201]
Usually, the header of the occurrence details contains the gathering date of the occurrence. If there is no gathering date, this should be "unknown" or just blank, but it's 1 January 1970 (see attachement).

![Unbenannt](https://user-images.githubusercontent.com/11058397/148562061-c50ac4c3-c062-4dd5-bacd-772ce4c5370e.PNG)

https://hp-herbarium-germany.gbif-staging.org/de/data.html?entity=1211532625&filter=eyJtdXN0Ijp7ImRhdGFzZXRLZXkiOlsiNzM3N2MyMTQtZTdmMS00ZmMwLWE5ZGUtM2I4NTcyOGNjYzExIl19fQ%3D%3D&from=0&view=TABLE

**Comment by MortenHofft** [comment]
Thank you for reporting it. It should be fixed now in staging
