### ISSUE TITLE
Table columns CollectionCode, InstitutionCode and Locality

### ISSUE THREAD

**Issue by jholetschek** [gbif/hosted-portals#208]
For our virtual herbarium, it would be nice to include CollectionCode, InstitutionCode and Locality into the table view.
Would it be possible to add them?

**Comment by MortenHofft** [comment]
Now added as `collectionCode, institutionCode, locality`.E.g.
`defaultTableColumns: ['recordedBy', 'dataset', 'country', 'features', 'catalogNumber', 'collectionCode', 'institutionCode', 'locality']`
