### ISSUE TITLE
Occurrence search map - configure extent/center/bounding box

### ISSUE THREAD

**Issue by rondlg** [gbif/hosted-portals#21]
Hi,

On this page: https://hp-north-america.gbif-staging.org/data?view=map

Is there a way for us to set the map extent to be smaller than global?

Thanks

Sharon

**Comment by jenningsdt** [comment]
Tangentially related: in navigation.yml, I changed the href for the Data menu item to /data?view=map and now the portal displays the map by default and zooms in a little better.

**Comment by MortenHofft** [comment]
@rondlg that isn't an option currently, but should be

@jenningsdt it remembers your zoom/bounding box, so it is only better on your machine. For everyone else it is as they left it last (default whole world).

**Comment by bienflorencia** [comment]
I think there's a comma missing after the brace here https://github.com/gbif/hp-north-america/blob/cab75f1fac53cbe2722d9184c1bd1ddf6c0d4d96/_includes/js/config.js#L12

**Comment by camiplata** [comment]
@bienflorencia yes it is, I added the comma an got the desired result (https://github.com/gbif/hp-colombian-biodiversity/blob/master/_includes/js/config.js).
Thanks @MortenHofft it helps a lot for the UX, I love how the map looks now. 

<img width="1041" alt="Captura de Pantalla 2022-02-22 a la(s) 8 39 11 p  m" src="https://user-images.githubusercontent.com/5700527/155248532-827f426a-f441-4acf-b221-175a6fc5331c.png">
