### ISSUE TITLE
new occurrence fields

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#210]
* degreeOfEstablishment (new field normalised to vocabulary)
* pathway (new field normalised to vocabulary)
* verticalDatum : string that is not interpreted
* verbatimIdentification : string that is not interpreted

@MattBlissett is it correct that verticalDatum and verbatimIdentification is uninterpreted strings please?

**Comment by MattBlissett** [comment]
Yes, correct.

**Comment by MortenHofft** [comment]
verticalDatum and verbatimIdentifications added in https://github.com/gbif/gbif-web/commit/ce24b7d06c6f84d7c673905a5e9c1c25e1e02e0f

**Comment by MortenHofft** [comment]
pathway and degreeOfEstablishment added to web API in https://github.com/gbif/gbif-web/commit/0441f2f81e6a9b6e1ed948487f24fa4325ae865c, but still needs added to GRaphQL schema and react components

**Comment by MortenHofft** [comment]
@MattBlissett Are there any issues related to these fields?
I do not see any in https://api.gbif-uat.org/v1/enumeration/interpretationRemark
