### ISSUE TITLE
Data Page - Keyword search

### ISSUE THREAD

**Issue by rondlg** [gbif/hosted-portals#22]
Hi,

On this page: https://hp-north-america.gbif-staging.org/data

A key feature on the data page should be a singular "Keyword Search" akin to the "Search all fields" on the main GBIF site. 

We're not sure if the "Similar Text" search button is supposed to be a keyword search but the description implies that it isn't quite and when you use it results are not a we expected.

Thanks

Sharon

**Comment by tucotuco** [comment]
Super important for VertNet that this works twoo. The Similar Text
corollary there is the default way people enter the site, everything else
is advanced. This is not to say that we need or even want to model the user
experience to be that same duality, just that the full text search is an
all-important capability.

**Comment by dbloom** [comment]
Yes and yes. John beat me to a response, but I agree heartily. A field for text is a very important piece for a portal. At the moment, we all have this feature (GBIF, iDigBio, VertNet, Canadensys, etc.). Our experience is that it is probably the most used means to begin a search - even if a user knows what he or she is looking for. It is also a fundamental tool in discovery when a user does NOT know exactly what he or she might need or want to find. Further, I admit to pushing this issue (sometimes without grace) during VertNet and GBIF NA Regional discussions about their respective hosted portals.

**Comment by MortenHofft** [comment]
Similar search should do the exact same as on gbif.org (or at least very similar). If it doesn't then it is a bug. We updated ES recently, and the way free text search is done has changed, it sounds a lot like I haven't adapted the search functionality.

Thank you for pointing it out.

**Comment by MortenHofft** [comment]
@rondlg and @tucotuco could you please give an example of a search using the "similar text" filter and describe 
* what it does
* what you had expected it to do
* how it differs from GBIF.org

It behaves as I expect, but I might well be missing something. Here is a [search for `road kill`](https://hp-north-america.gbif-staging.org/data?filter=eyJtdXN0Ijp7InEiOlsicm9hZGtpbGwiXX19&view=gallery)

Thank you for your help

**Comment by albenson-usgs** [comment]
I'm probably not the best person to comment on this ticket as I don't normally do free text searches on GBIF and I don't have any users that request it but when I searched for "Colorado" using Similar Text [here](https://hp-north-america.gbif-staging.org/data) I get back 0 results. I'm not sure I had an expectation of how many results but more than 0. 

I also tried searching "Branta" which is one of the first genus listed in the Table view and it also brings back 0. Which fields is the "Similar Text" searching in?

**Comment by MortenHofft** [comment]
Aha, it is a casing issue. Thank you @albenson-usgs 
No results for Colorado or Branta, but plenty for colorado and branta

**Comment by MortenHofft** [comment]
A [search for Colorado](https://hp-north-america.gbif-staging.org/data?filter=eyJtdXN0Ijp7InEiOlsiQ29sb3JhZG8iXX19) now gives results.

@rondlg does this solve the issue? What would be a more appropriate name for the filter? 

On GBIF.org the flow is like this: I write my danish english => communication then translate that into proper and non insulting english => and that version is then made available to translators. We could consider something similar for this project. That would give you (if you cared to) the option to correct all english labels.

**Comment by rondlg** [comment]
Cool - I like simple solutions.

If we just go with "Keyword Search" to start with, that would be a help.

**Comment by tucotuco** [comment]
In VertNet we call it a "full text search". Keyword to me suggests that
there is a subset of words that will retrieve results, but that is not the
case.

To answer an earlier question, in VertNet that search is against an index
built on a subset of all Darwin Core fields. Some do not make sense to use
in the search. If of interest, I can provide that list.

**Comment by MortenHofft** [comment]
This one does not search all fields either (neither does the GBIF.org one despite the name). Personally I'm not crazy about `keyword search` either. 
* Technically it isn't keywords, keywords are exact, this is fuzzy.
* And the form is different. We do not call the other filters `Basis Of record search`

But I'm happy to let someone else decide. What about just `Free text` for the button?

**Comment by tucotuco** [comment]
"Full text" did not raise any confusion that was communicated in our
community over the last nine years, so probably safe.
