### ISSUE TITLE
literature limit not working

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#220]
We recently moved the literature endpoint from using APIv1 to go straight to ElasticSearch (this was done to allow users to have richer scopes). In that process the limit parameter stopped working.

**Comment by albenson-usgs** [comment]
@MortenHofft would this be the reason the literature on gbif.us is not paging correctly? The issue is that no matter what page you go to it's the same papers listed.

**Comment by MortenHofft** [comment]
It sounds likely, though at the time when I created this issue it was my conclusion that this only mattered for a single user of the unstable API and hence wasn't a priority. I will check, it sounds a lot like I've missed something!

**Comment by MortenHofft** [comment]
It is fixed and is deployed to staging

**Comment by frafra** [comment]
@MortenHofft Thank you, it was easy to fix that thanks to your message :) https://github.com/gbif/hp-living-norway/commit/851e50e905c68e940e57ebd508a4930c6b52240c
