### ISSUE TITLE
Occurrences don't show in map when free text filter is set

### ISSUE THREAD

**Issue by jholetschek** [gbif/hosted-portals#225]
The free text fiter is very useful for non-scientific users. However, it seems not to work on the Map view. For example, there are a lot of hits for "berlin", many with coordinates (for example all records in the dataset "herbarium willing"). However, they don't show up in the map:
https://herbarium.gbif.de/de/data/?datasetKey=85727f1e-f762-11e1-a439-00145eb45e9a&q=berlin&view=MAP

The number of records with coordinates matching the filter is correct.

**Comment by MortenHofft** [comment]
Ouch yes. I realize in this moment that we broke that when we starting using our new maps 3 months ago!
That isn't good.

We had an existing maps service (which supported free text), but we then starting using a new service that supports multiple map projections. But in that process we lost the free text query support.

We will get it back, but I do not have the overview just now to say how much work is required.

Thank you for raising it!

**Comment by MortenHofft** [comment]
@jholetschek it isn't solved yet, but here is an update. 
The API needs to be extended with a new predicate type to support free text queries. Something along:

```json
"predicate":{
  "type":"fullTextSearch",
  "value":"dog"
}
```

Once that is in place the hosted portals needs to be updated to use the new format.

ping @fmendezh

**Comment by MortenHofft** [comment]
I've implemented solution 2 from https://github.com/gbif/occurrence/issues/288#issuecomment-1130211723 in a branch and deployed it to staging. Have you considered removing the free text option for now @jholetschek?
It isn't a good way to search for data in Berlin anyway 😄  - just see the results below. Looking at that you would think Berlin was a synonym for Greece

https://hp-herbarium-germany.gbif-staging.org/data/?q=berlin&view=MAP

**Comment by jholetschek** [comment]
Hi Morten,

yes, Berlin yields too many hits, since it's part of all our dataset titles. Also of Herbarium Willing, a collector who gathered like crazy in Greece!
But since the portal is intended not only for scientists, the filter is great, since it allows to find famours collectors easily:
https://hp-herbarium-germany.gbif-staging.org/data/?q=humboldt&view=TABLE 

Thanks for fixing this!
Jörg
