### ISSUE TITLE
filter occurrences with networkKey

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#231]
Hello,

May I know if it is possible to have an [Occurrence filter](https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/search/OccurrenceSearch/config/filterConf.js) for networkKey?

Ideally it would be great if we can have the option to indicate the filter (networkKey) under highlightedFilters in config.js

The idea is to have all the antarctic data within the polygon and users can filter for occurrences associated with [SCAR](https://www.gbif.org/network/8534dd20-c368-4a1f-bdaf-e6b390710f89) or [OBIS](https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6) network.

https://github.com/gbif/hp-antarctic/issues/1

**Comment by MortenHofft** [comment]
We can. the problem is that it isn't scoped to the data of your site. So it would suggest any network. I do not have a handy solution ready to add that is scoped per site. I will add the networkKey option and give other options some thought. Feel free to poke me again

**Comment by MortenHofft** [comment]
@fmendezh adding networkTitles to the occurrence Index would likely solve it I believe (just like we add datasetTitles and publisherTitles)

**Comment by ymgan** [comment]
also yes, it seems to be working!! Thank you so much!!
