### ISSUE TITLE
Get identifierBadge for DOIs

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hosted-portals#237]
Hello ! 
I was wondering if it's possible to have the DOI identifierBadge that GBIF displays in the datasets' references as a feature (example). 

![image](https://user-images.githubusercontent.com/25744687/191682316-289bbdc9-d8e9-4d13-8e6c-5800ebf9ecd8.png)

Found this, but I'm not familiar enough to bring it to the `main.scss`.
https://github.com/gbif/gbif-web/tree/master/packages/react-components/src/components/IdentifierBadge

Thanks a lot!

**Comment by MortenHofft** [comment]
I'm not sure I understand. The DOI is already being showed as in the above example. Or is it nor working properly? Or do you want to show it elsewhere? Sorry - I need a bit more details please.

**Comment by MortenHofft** [comment]
Reading this again. Is it because you wish to show DOI elsewhere on the site (in the markdown driven pages) and want to use the same styling?

**Comment by bienflorencia** [comment]
Sorry about that, Morten! Yes, I'm interested in showing the badge in a list of publications outside that (https://hp-biodiversidata.gbif-staging.org/recursos/publicaciones/)

**Comment by MortenHofft** [comment]
Hmm, there isn't a very good way to reuse that in your context. The medium good way would be to use react, but that is cumbersome for you.
Then you could copy html part, and the style, but then they could deviate over time. It is probably the simplest I'm afraid

```
<a class="myDoi" href="https://doi.org/10.2307/25065646"><span>DOI</span><span>10.2307/25065646</span></a>
```
and style from https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/components/IdentifierBadge/styles.js

**Comment by bienflorencia** [comment]
Thanks Morten! It's working :)
https://hp-biodiversidata.gbif-staging.org/recursos/publicaciones/ 

<img width="793" alt="imagen" src="https://user-images.githubusercontent.com/25744687/192106522-21fbc188-a1fa-48d9-94ac-f2ad9c7eec5b.png">
