### ISSUE TITLE
How to add GBIF node logo in the footer?

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#239]
Hi,

As mentioned in the [node logo guidelines](https://assets.ctfassets.net/uo17ejk9rkwj/47acC3NY0cphRIaqyoWJoV/43f2b12afc527a975efdf9384aa87f8f/node-logo-guidelines.pdf), we would like to add the GBIF node logo in the footer of the antarctic hosted portal. However, I couldn't find a way to do it.

@rukayaj and I have explored the html [here](https://github.com/gbif/jekyll-hp-base-theme/blob/master/_includes/footer.html) but it doesn't seem like it is possible to add a logo as depicted in page 8 of the [node logo guidelines](https://assets.ctfassets.net/uo17ejk9rkwj/47acC3NY0cphRIaqyoWJoV/43f2b12afc527a975efdf9384aa87f8f/node-logo-guidelines.pdf) (see screenshot below)? Can you please advise how can we do that? Thank you so much!!

Related issue: https://github.com/gbif-norway/helpdesk/issues/115 

![Screenshot 2022-09-26 at 14 38 14](https://user-images.githubusercontent.com/11754081/192278036-e4345e1a-089e-4ff6-9d05-4b3f8c841348.png)

**Comment by MortenHofft** [comment]
You could add something like this as a new column in your footer.

```
columns:
  - description: |
      <img src="/assets/images/your-image.png" width="150" />
```

**Comment by ymgan** [comment]
Ahhh~~ You are the best Morten!! It works!! Thank you so much!!
