### ISSUE TITLE
checklist dataset search not working

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#247]
When we try to do any search using the dataset/checklist tab we get the same 'total' result

Example of a query by publisher:

https://biodiversidad.co/dataset/search?anyPublisherKey=2a7e3080-28a9-11dd-97cd-b8a03c50a862&type=CHECKLIST

<img width="1551" alt="Captura de Pantalla 2022-11-15 a la(s) 11 31 37 a  m" src="https://user-images.githubusercontent.com/5700527/201897328-d971c347-838a-4b0d-a7fa-348bf91c0536.png">

**Comment by MortenHofft** [comment]
Looks like we introduced this error with the merge of ALA event search. We have split publisher filters into 2 - one driven of occurrence scope and one that look into all of gbif publishers. But the naming leads to conflicts. And it seem to expose a more fundamental problem in how we reuse names for filters.

**Comment by camiplata** [comment]
Thank yout Morten
