### ISSUE TITLE
png background image in home has a dark background

### ISSUE THREAD

**Issue by bienflorencia** [gbif/hosted-portals#251]
Hi @MortenHofft  

I wonder why I see the background of these png files correctly on my local version but not on the staging site. Any suggestions? 

My local view:

<img width="1005" alt="imagen" src="https://user-images.githubusercontent.com/25744687/213924976-5089e1b8-a35f-4f43-a36a-1a807346e008.png">

At the https://hp-biodiversidata.gbif-staging.org/:

<img width="1043" alt="imagen" src="https://user-images.githubusercontent.com/25744687/213925105-46bb395c-8e36-4278-98e1-ac72e70ad4d8.png">

Edit: the code for this is [here](https://github.com/gbif/hp-biodiversidata/blob/master/_data/home.yml#L7)

**Comment by MortenHofft** [comment]
I'm pretty sure that is because the staging site runs them through Thumbor. And in that process the transparent background of your png is being transformed into black. Let me check

**Comment by MortenHofft** [comment]
Yes that is indeed the case.Yes, that does indeed seem to be the case. I can probably fix that. In your end the only thing you can do is to: wait for me **OR** change your image to have a solid background

**Comment by bienflorencia** [comment]
I can wait :) Thanks a lot!

**Comment by MortenHofft** [comment]
Looks better now - thanks for reporting
