### ISSUE TITLE
Images not found for Gallery view for portals on Staging

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#256]
For example:

- https://antarctic.hp.gbif-staging.org/occurrence/search/?view=GALLERY
- https://beaty-biodiversity-museum.hp.gbif-staging.org/specimen/search?view=GALLERY

The requests of the images return 404. It only happens to portals at staging. 

Can you please have a look at it? Thank you so much!

**Comment by MortenHofft** [comment]
Thanks - we started scaling images in a different manner and I hadn't added the necessary config to all environments. Sorry about that. And thank you for bringing it up!
