### ISSUE TITLE
literature search filter and view in hosted portal

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#257]
Hey,

@antonarctica and I just had a look at literature search in the hosted portal. We have some questions:

The current view (below) feels a little limited in context because we do not know how each literature record is associated with GBIF or data with GBIF. 

![Screenshot 2023-07-11 at 13 40 37](https://github.com/gbif/hosted-portals/assets/11754081/cedb8eb8-1aea-4e93-a9da-e03a3bfdbf90)

I think it will be nice to have the [relevance](https://www.gbif.org/developer/literature#p_relevance) filter (for some reason I could not add that filter to the config) or column in the search results. We will appreciate if there could be some indication to show **how** the literature is associated with GBIF, whether it uses/cites data from GBIF or contributing data to GBIF. If it is just me not understanding how to use the API, it will be great if you could please help me with that (not urgent btw).

We think that these could potentially help the users to understand what they can look for using the literature search. Thanks a lot!!

**Comment by timrobertson100** [comment]
Please can you try and add a `relevance` filter in your configuration? 
With Morten on holiday, I can't ask today but I imagine it may well be supported.

**Comment by ymgan** [comment]
I have added `relevance` filter here in my config: https://github.com/gbif/hp-antarctic/commit/a0266c6ccc8e19c91cb007dd99a664aeee0ed5d0# 

but it doesn't seem to show up in the hosted portal https://hp-antarctic.gbif-staging.org/literature/search

**Comment by timrobertson100** [comment]
Thanks.

I think this requires a code change somewhere around [here](https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/search/LiteratureSearch/config/filterConf.js). It appears listed in the GraphQL API, but indeed isn't available as a filter. Can this wait 2 weeks, please, as with everyone out on holiday I'm concerned I could unwittingly break something...

**Comment by ymgan** [comment]
Thank you very much for looking into it @timrobertson100 I really appreciate it!

No worries at all, totally understandable! It is not urgent from our side, definitely not a problem to wait for 2 weeks (or more if your team needs it!) :)

**Comment by MortenHofft** [comment]
It is in staging now, does it do what you expect it to? 
There is a relevance column in the table and a relevance filter. Similar for topics.

I will put it in production next week

**Comment by ymgan** [comment]
Thank you so much for making this work, @MortenHofft !! You are a superstar!! 🌟 

Yes, that is how I expect it to work! I will check with Anton and perhaps our users :) If there are more suggestions for improvement, I will open a separate issue :D Thank you so much!
