### ISSUE TITLE
Add more social icons with links

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#27]
From mailing list

> How can we add facebook and youtube or any other relevant social media links?

**Comment by jocelynpender** [comment]
Can we add a GitHub link as well, with logo, similar to twitter etc.?

**Comment by MortenHofft** [comment]
That has been there all along. I'll add an issue to document the options as it is hard to know.
 
In case of the canadian portal it was [removed in this commit](https://github.com/gbif/hp-canadian-biodiversity/commit/7a1cef4c94411ccf4a799535c7a867780505bb1f)

**Comment by bienflorencia** [comment]
Hi Morten, is it possible to add Flickr as social icon?
Cheers!

**Comment by MortenHofft** [comment]
> Hi Morten, is it possible to add Flickr as social icon? Cheers!

Added: `flickr_username: something` in `_config.yml`
