### ISSUE TITLE
Exclude datasets in filter

### ISSUE THREAD

**Issue by T-Engel** [gbif/hosted-portals#270]
**Is your feature request related to a problem? Please describe.**
I would like to use the dataset filter to exclude specific datasets. For example, I want to include all datasets but "naturgucker".

**Describe the solution you'd like**
A dropdown menu with all datasets so they can be ticked and unticked (might not scale well if many datasets are in the portal)

**Describe alternatives you've considered**
Alternatively, is there a syntax for exclusion that can be used in the current version of the filter? something along the lines of " dataset != naturgucker"

**Additional context**
in the screenshot below, it would be great to see all the available datasets so one can manually select.
![image](https://user-images.githubusercontent.com/37897372/225651721-01f0db38-1b58-4f65-a377-411cbe227cb8.png)

Cheers!

**Comment by MortenHofft** [comment]
This is now possible by providing an overwrite for the individual filters. enum filters and suggest filters support it.
Here is an example from hp-land where the dataset filter is extended to support negations
https://github.com/gbif/hp-land/blob/97d986c2bd79092ef4ce7409c4fc6e0f589a2cd6/_includes/js/config.js#L72

```js
filters: {
  datasetKey: {
    merge: true, // merge the settings with the already defined dataset filter
    config: {
      specific: {
        supportsNegation: true // the only field that we want to change
      }
    }
  }
}
```

**Comment by jholetschek** [comment]
This is perfect - and it's also reasonably fast-
Thanks, Morten!
