### ISSUE TITLE
error when trying to download data selected in hosted portal

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/hosted-portals#271]
I believe I have discovered a bug in the download functionality from the hosted portal. I was attempting to download the observations for all species in the United States labelled Data Deficient by IUCN. I had selected that parameter in GBIF.us but when it sends me over to GBIF for the download I get "The predicate in the URL is invalid" error. https://www.gbif.org/occurrence/download/request?predicate=%7B%22type%22:%22and%22,%22predicates%22:%5B%7B%22type%22:%22and%22,%22predicates%22:%5B%7B%22type%22:%22in%22,%22key%22:%22COUNTRY%22,%22values%22:%5B%22US%22,%22UM%22,%22AS%22,%22FM%22,%22GU%22,%22MH%22,%22MP%22,%22PR%22,%22PW%22,%22VI%22%5D%7D,%7B%22type%22:%22not%22,%22predicate%22:%7B%22type%22:%22equals%22,%22key%22:%22ISSUE%22,%22value%22:%22COUNTRY_COORDINATE_MISMATCH%22%7D%7D%5D%7D,%7B%22type%22:%22in%22,%22key%22:%22IUCN_RED_LIST_CATEGORY%22,%22values%22:%5B%22DD%22%5D%7D%5D%7D#create

Is it user error or is this a bug?

**Comment by MortenHofft** [comment]
That is no doubt a bug. It shouldn't be possible to create an invalid filter using the UI. That would be evil. I'll look into it. Thank you for raising it. It isn't obvious to me what the error is at first sight

**Comment by MortenHofft** [comment]
The issue wasn't the predicate, but the validator. I suspect that I implemented that predicate validator before we had added iucn as a filter. And had missed to allow that option.

**Comment by albenson-usgs** [comment]
Thanks Morten!
