### ISSUE TITLE
Disable "set as filter" when clicking the text within cells in table view

### ISSUE THREAD

**Issue by mpitblado** [gbif/hosted-portals#274]
@MortenHofft is there a way that we can disable the "Set as filter" feature within the tables? In most UI (both on this site and in general), the text within a cell serves as the link to open the individual record, so users may be confused when the record doesn't open and the table shifts. On mobile, *the hover text will never appear* so new users will not know that they activated the functionality, and the text is harder to avoid in the cell even if the user tries not to click it on purpose

![image](https://github.com/gbif/hp-beaty-biodiversity-museum/assets/116753126/6d3498f9-ba9c-49d1-bd13-ea58065529bf)

**Comment by MortenHofft** [comment]
Hi @mpitblado you can now disable the feature site wide by adding below yo your site config. It is sitewide and not per table.
```js
disableInlineTableFilterButtons: true
```

I've also disabled it automatically on touch devices.
