### ISSUE TITLE
how to configure url of tags?

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#291]
Hey, 

May I know how can I configure the url of tags when they have different translations please?

### English version

https://www.canadensys.net/

![Screenshot 2024-05-31 at 16 06 48](https://github.com/gbif/hosted-portals/assets/11754081/220240f7-9d86-470e-a7d1-48897561bdd1)

Tag url for `Conference` is https://www.canadensys.net/news/?category=Conference

### French version

https://www.canadensys.net/fr

![Screenshot 2024-05-31 at 16 08 22](https://github.com/gbif/hosted-portals/assets/11754081/bcf74436-1389-48c1-ab86-1f1572a517c5)

The tag url for `Conférence` become https://www.canadensys.net/news/?category=Conf%C3%A9rence which returns nothing because it is missing the `fr/` prefix - https://www.canadensys.net/fr/news/?category=Conf%C3%A9rence

Thanks a lot for your help!

**Comment by MortenHofft** [comment]
You need to define where you news archive is located per language. Else it will use a default
https://hp-theme.gbif-staging.org/translations#where-is-the-post-archive

**Comment by ymgan** [comment]
Thank you so much Morten!
