### ISSUE TITLE
possible to have a separate staging for translation?

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#293]
Hey,

We are currently working on translating our hosted portal into French, Spanish and Russian. May I know if it is possible to have another staging to view the (ongoing) translated site, maybe on a separate branch? It's not always easy to have them to run the hosted portal locally. 

Meanwhile Anton and my colleagues also wanted to post news and announcements on our hosted portal while the translations are ongoing.  

Any advice is appreciated! Thanks a lot!

**Comment by MortenHofft** [comment]
You can disable those languages in staging, then you will only see them in uat. Or you can disable them in prod only to still see then in staging.

from grscicoll
https://github.com/gbif/hp-grscicoll/blob/master/_config.yml#L97 exclude french and some other languages in prod

and then you can add a uat config that includes french in that domain
https://github.com/gbif/hp-grscicoll/blob/master/_config_uat.yml#L5

**Comment by ymgan** [comment]
OH!!! Thank you so much Morten!!! that makes sense, I forgot that there is also uat!!

**Comment by ymgan** [comment]
@MortenHofft Did I do it right? 

config_uat.yml: https://github.com/gbif/hp-antarctic/blob/b76ceedf0479bce67d42955e7378f6ea0c4f8e98/_config_uat.yml#L3

The change does not seem to be reflected on uat: https://hp-antarctic.gbif-uat.org/
