### ISSUE TITLE
Interfaz displaying an incorrect date in related resource tab

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/hosted-portals#298]
There looks to be a mismatch in date displayed when I look in our hosted portal in related resources tab. In this record of [Cryptotis thomasi](https://biodiversidad.co/data/?datasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7&entity=3113468636&isInCluster=true&taxonKey=359&view=TABLE) it showns 11 may for the related occurrence:
![Image](https://github.com/user-attachments/assets/fbca8a34-f244-463e-a1a9-ea172d79c770)

And it looks weird considering that they are supposed to be clustered because they have some equal information.

But when I look for that occurrence in GBIF it shows 12 of may: https://gbif.org/occurrence/3710474697
![Image](https://github.com/user-attachments/assets/c3055487-e385-4402-9752-77e38168c86d)

And it is shown correctly in occurrence search in GBIF ![Image](https://github.com/user-attachments/assets/2995f83a-7ba9-4e06-bcab-a2e18be8ab06)

No idea why it is showing some dates mismatched by one day, but other records were behaving similarly.

Thanks in advance,

**Comment by MortenHofft** [comment]
I  haven't looked yet, but I'm 99% sure it is because it is using the browsers timezone when formatting the date. I probably didn't properly specify that it should use UTC. And dates used to include the timezone, but after a change within the last year in how we handle dates, precision and ranges, then the timezone `Z` is not longer included in the date string. And so the formatting falls back to using local time.

**Comment by MortenHofft** [comment]
I've looked and annoyingly I do not really get it. The first time shows correctly with hours. And the second that only has date resolution shows the wrong date. Neither of them has a time zone specified. So I would have expected the browser to handle them the same.

Anyhow, I've tried to be more explicit and add `Z` when not specified to the interpretation. And then similarly define it as UTC when displayed. That should hopefully fix it. Could you please check the behaviour in staging?
