### ISSUE TITLE
Establish GH repo for each portal

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hosted-portals#3]
Setup a GH repo with the initial codebase for each portal

**Comment by MattBlissett** [comment]
One way to do this is to mark the source repository as a template, then it can be duplicated (with a squashed history) as a new project within GitHub.  doc-template is used like this for new documents.

**Comment by MortenHofft** [comment]
Here is an attempt to keep the applicants portal names in the repo naming. I have also tried a giving them normalised names, but it wasn't easy and it seems more confusing than helpful. I think I would be in favour of something akin the `Somewhat faithful` column. 

|Portal name in application|Somewhat faithful|Attempt at normalised|
|-------|----------|--------|
|VertNet Plus|hp-vertnet-plus|hp-group-vertnet|
|Biodiversity Information Serving Our Nation (BISON)|hp-bison|hp-country-us|
|BIODIVERSIDAD.CO - Colombian Biodiversity Portal|hp-colombian-biodiversity|hp-country-columbia|
|Canadian Biodiversity Portal|hp-canadian-biodiversity|hp-country-canada|
|Global Biodiversity Information Facility - Pacific|hp-sprep|hp-region-sprep|
|Legume Data Portal|hp-legume|hp-group-legume|
|GBIF North America|hp-north-america|hp-region-na|
|Portal de la Región de Latinoamérica y Caribe|hp-latin-america-caribbean|hp-region-lac|
|SANBI-GBIF Website Platform|hp-sanbi|hp-country-south-africa|
|Virtuelles Herbarium Deutschland/Virtual Herbarium Germany|hp-herbarium-germany|hp-group-herbarium-germany|
|Virtual Collection of the Natural History Museum Rotterdam|hp-nhm-rotterdam|hp-museum-nhm-rotterdam|
|Living Norway Ecological Data Network|hp-living-norway|hp-group-living-norway|
|https://www.ngbif.org.ng|hp-ngbif|hp-country-nigeria|
|SIBUy|hp-sibuy|hp-country-uruguay|
|Mapping Asia Plants (MAP)|hp-mapping-asia-plants|hp-group-map|
|KenBIF|hp-kenbif|hp-country-kenya|
|GBIF Benin - Biodiversity data portal|hp-benin|hp-country-benin|
|ASEAN Region Hosted Portal|hp-asean|hp-region-asean|

**Comment by timrobertson100** [comment]
> I think I would be in favour of something akin the Somewhat faithful column.

I agree too
