### ISSUE TITLE
Display the occurrenceSearch from GBIF-UAT and not GBIF prod ?

### ISSUE THREAD

**Issue by morelanneIF** [gbif/hosted-portals#300]
Is it possible to **temporarily change the source of the data displayed in occurrence search from GBIF prod to GBIF-UAT** ? I could not find the api.gbif-uat anywhere....
The reason behind this is that the data we want to display is not yet published on GBIF prod, but we still would like to display the testing data we have on GBIF-UAT.

Thank you for your help

**Comment by ManonGros** [comment]
Would https://swissnatcoll.hp.gbif-uat.org show the data from UAT?

**Comment by morelanneIF** [comment]
At the moment we use https://swissnatcoll.hp.gbif-staging.org. We would need this only until the 27th of January 2025. I don't know yet when we are going to do the first release of our hp.

Sorry if my enquiry is a bit weird.... I just would like to assess how this change can be done, if doable, and how much work it represents. If I can do something on my side that is also reversible, it would be awesome.

**Comment by ManonGros** [comment]
Why not use https://swissnatcoll.hp.gbif-uat.org/? It is the same website, just with data coming from UAT.

**Comment by morelanneIF** [comment]
Oh awesome ! Thank you, I didn't know that. Perfect.
Thank you, have a nice day.
