### ISSUE TITLE
spacing of logo + title + menu

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#38]
On some sites logo, title and menu overlap. That shouldn't happen unless custom css is added

<img width="141" alt="Screenshot 2021-03-02 at 12 58 09" src="https://user-images.githubusercontent.com/6759267/109645481-31095b00-7b57-11eb-805c-d42d6ee20ecf.png">

**Comment by MortenHofft** [comment]
I'm not really an expert on SVGs, but the markup in above example seemed somewhat cluttered. And I can see in the source code that it is auto generated by Adobe. Reading a bit I can see that it is a problem others also encounter now and then when using generated SVGs. Not that I would know how anyone could reasonably be expected to handcraft them.

The issue was caused by the SVG logo not specifying its size. Or at least it can be fixed by setting it.
e.g. `width="100px" height="100px"`

So the initial commit will have not have shown the logo
https://github.com/gbif/hp-canadian-biodiversity/commit/6fd9bb922470a6960ada04dc8e288d24a2004a28

When the site name was added next to it, the container suddenly had a size so it appeared with a height, but the width was still missing and so the elements would overlap.
https://github.com/gbif/hp-canadian-biodiversity/commit/b7668d11cb0bc595092effe3b75aab7343663f8c

Fixing the SVG size resulted in a proper layout again
https://github.com/gbif/hp-canadian-biodiversity/commit/0a34bd38a00d0b217efc0b84364b45080171551b

**Comment by MattBlissett** [comment]
I don't have Adobe, but I think there might be options to save as a "web" SVG or similar, which can help with compatibility etc.

(I have been known to hand-edit SVGs. [This one](https://rs.gbif.org/style/logo-tessellate.svg) for example.)

**Comment by MortenHofft** [comment]
I believe you are right.

And if anyone needs an artisanal hand coded SVG or simply need their soulless Adobe icon fixed, then we now know someone who can help us 😄
