### ISSUE TITLE
Create VM(s) and automatic build/deploy pipeline for each portal

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hosted-portals#4]
The portals are Jekyll SSGs each held in a GH repository. We need to design and implement a build workflow that automates the deployment of them onto one or more VMs (e.g. a Jenkins job triggered by a commit or release).

**Comment by MortenHofft** [comment]
Should we 
* add `--unpublished` to staging so that authors can preview their data?
* And run `JEKYLL_ENV=production jekyll build` for production.
* Compress files
* Add cache headers for assets

**Comment by MattBlissett** [comment]
I don't see any official documentation on what the recommended configuration for Apache, Nginx etc would be.  Do you know of any? (Is self-hosting really this unusual nowadays?)

**Comment by MattBlissett** [comment]
All four issues Morten raises are solved. The build script is /usr/local/bin/hosted-portal-build-deploy on Jenkins, and they can all be seen here: https://builds.gbif.org/view/Hosted%20Portals/

https://dev.gbif.org/hosted-portals.html has links to each portal, on production and staging.

**Comment by MortenHofft** [comment]
staging doesn't include unpublished pages (which might be fortunate as I've added an unpublished language splash page), but from our discussion the other day the decision was to add that flag (as I understood it)

**Comment by MattBlissett** [comment]
This should be fixed.

I can't prevent GitHub triggering four builds (release created, release released, release published, normal build) but for the "created" and "released" steps I just end the build.
