### ISSUE TITLE
Occurrence search maps: projections

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hosted-portals#69]
We currently use Mapbox - we should use openlayers.

Mapbox only support the mercator projection. And they aren't open source anymore.

We need to have an option for arctic data. On gbif.org we use OpenLayers. Open layers are great, but MapBox performs better and is prettier. 

Including support for both libraries are costly in developer time and adds kb to the js file. We should evaluate open layers as the only map library.

**Comment by MattBlissett** [comment]
It doesn't solve the projections issues, but the people behind OpenMapTiles forked MapBox GL to MapLibre: https://github.com/maplibre

It's very recent though, so I think OpenLayers is still the better choice.

**Comment by MortenHofft** [comment]
See https://hp-theme.gbif-staging.org/data-exploration-config#map-options
