### ISSUE TITLE
Error in gallery view

### ISSUE THREAD

**Issue by tucotuco** [gbif/hosted-portals#8]
After constructing a query with results and switching to the gallery view (https://hp-vertnet-plus.gbif-staging.org/data?filter=eyJtdXN0Ijp7InRheG9uS2V5IjpbMjQzOTYwOF0sImRhdGFzZXRLZXkiOlsiNWE2NTkyNDgtMWY3MC0xMWUzLWIyYzUtMDAxNDVlYjQ1ZTlhIl19fQ%3D%3D&view=gallery), the area where images should appear contains just the word "Error". I suspect this is a case where there are no images for records that match the query conditions.

**Comment by MortenHofft** [comment]
Thanks - we had updated the index to ES7, but the API hadn't been probably adjusted. Thank you for mentioning it. It is fixed and deployed

**Comment by tucotuco** [comment]
Confirmed goood, Thanks.
