### ISSUE TITLE
Footer Powered by  GBIF  + 

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#97]
Hi @MortenHofft it is posible to add SiB Colombia to the Powered By at the end of the page? something like: 

Powered by GBIF and SiB Colombia

**Comment by kcopas** [comment]
@camiplata the point of the "powered by" branding (which I'm in the course of developing now) is that it will consistently means identify the hosted portals as served by the GBIF infrastructure. We will maintain it across all hosted portals. The portals themselves have an abundance of opportunties for the site owners' branding. So the "powered by" space is not intended as a co-branded one, no.

**Comment by camiplata** [comment]
@kcopas ok no problem then, I also prefer the idea of having a logo as mentioned on the [Canadian portal issues](https://github.com/gbif/hp-canadian-biodiversity/issues/7) to avoid translations of the "Powered by"
