### ISSUE TITLE
Standard width of layouts for text

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#98]
Hi @MortenHofft, the layouts have a fixed preestablished width for text that feels small, I was doing a trial in an 11'' screen and there is still a lot of room. Will it be possible to increase the preestablished width without affecting the responsiveness of the page for other devices? I think this could be usefull for everyone.

**Comment by camiplata** [comment]
Probably with the navigation bar plus toc it will be too much, maybe we can increase the width for the rest of the layouts and not for the documentation one.
In a 16'' screen there is still space even with the three elements https://hp-colombian-biodiversity.gbif-staging.org/formacion/laboratorios/DataValidator:

<img width="1792" alt="Captura de Pantalla 2021-03-15 a la(s) 3 48 27 p  m" src="https://user-images.githubusercontent.com/5700527/111219846-76417a00-85a6-11eb-82fe-9ef232322fb4.png">

But I don't want to go against the good practices "60-80 characters per line", we will have an internal check about this topic again, maybe meanwhile other portals can tell us about their individual preferences.

**Comment by MortenHofft** [comment]
Unless there is a general interest in this, then I think you should simply add your own css to solve this. You can experiment with the Bulma variables as well as add custom css.

.e.g. 
```
.article {
  max-width: 70rem; /* default is 45 rem */
}
```

If it is the content of a specific page you have in mind (I suggest being fairly consistent with widths though), then you can target specific pages as we did in https://github.com/gbif/hp-colombian-biodiversity/issues/10

**Comment by MortenHofft** [comment]
I'll be happy to help you if needed, but at this point I do not believe it requires any changes in the theme. And so it belongs in your project repo as a custom issue.
